### ISSUE TITLE
Relocate faction spawns to static bases

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#1073]
Relocating faction spawns to static overmap objects ensures players have something to consider defending.

**Comment by ghost** [comment]
I'd suggest the following:

Ensure the bases can't spawn within range of eachother or planets, so they can't abuse their weaponry in anything other than a defensive sense

Make bases immune to space combat, so that boarding is required to destroy them, either with one of the soon to be made capture points or a destructible object tied to the base's spawns. When destroyed, it would disable spawning.

**Comment by DexterDude** [comment]
UNSC get a SMAC for the superweapon and it makes the most sense, as that's the only UNSC space station I know. Covenant could get some unyielding hierophant looking thing with two energy projectors. URF would get...something. Maybe a captured SMAC?

I would say that the weapons should fire anything not a part of their faction, and they should be marked on nav computers so people don't accidentally stumble upon them and die horribly.

**Comment by daPotato** [comment]
URF could get a better asteroid + MAC on it so its not just a copypasta of the UNSC, and hide it in an asteroid field. UNSC can't drop directly into the base, but have to EVA to it.


> Another thing i have also considered is a full UNSC facility on a planet
shit with bunks, commons, a full training area
maybe a TTR arena

from discord

**Comment by DexterDude** [comment]
I could do that. Probably a better idea anyway.

**Comment by X0-11** [comment]
Groundwork towards this goal has been created in #1149 and #1116

**Comment by X0-11** [comment]
Finalised in #1198
