### ISSUE TITLE
Add overmap clutter

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#1156]
The current emptiness of the overmap is alleviated somewhat by the presence of NPC ships when spawned in by an admin, however, other overmap clutter and hazards to avoid or investigate would provide players with a reason to explore the map.

Examples of clutter would be wrecked ships, fragments of ancient forerunner structures embedded into asteroids or even just mine-able asteroid fields.

**Comment by SuckMySocks** [comment]
Idea boi here.

Derelict Vessels (recommend having rare/uncommon items inside, maybe a small story of what happened. Vessel should be mostly intact)

Wrecked Vessels (mostly debris with small-medium chunks, will most certainly need a space suit in order to survive) 

Mineable Asteroids (low-high tier materials, maybe minor relics for the Covies? Maybe a NPC dungeon on one of the asteroids?)

Debris (maybe just spess clutter? damages ships if they go through it?)

NPC Dungeon Vessel (a halted vessel with NPC’s inside that are harmful to all factions. Low-High tier gear. Maybe the end of the Dungeon has a type of reward generator?)

Yonhet Trader Vessel (Non-Covenant aliens that trade in rare weapons/armor? Maybe high tier RnD stuff, or base SS13 alien weapons/armor modified to fit the purpose?)

Flood Asteroid (Entire Asteroid that looks normal on the overmap, but if you mine to far you’ll find a big ol’ flood nest! Kill your way through a bunch of flood forms, eventually arriving at the end, fighting the final boss, the Juggernaut. Potentially an old ONI base?)

Might be back with more

**Comment by caelaislinn** [comment]
Right now I don't want more zlevels of clutter. A couple of derelict ships would be nice but all this needs is randomly generated asteroids, meteor showers, non mineable comets, gas clouds, ion storms, solar flares, dust patches, ice fields etc

**Comment by BDpuffy420** [comment]
@X0-11  for this can we atleast get some NPC ships spawning at round start add more life to the overmap

**Comment by caelaislinn** [comment]
# not sure when, added in XO's space weather PR
