### ISSUE TITLE
[SUGG]Add a Spartan-II role for the UNSC 

### ISSUE THREAD

**Issue by Plaguewalker** [HaloSpaceStation/HaloSpaceStation13#1217]
At this point UNSC is kinda lagging behind in the whole set of things. I'm proposing that we add a spartan role now at round start seeing as lore wise we're at the point in FC where the S-II's would be in full operational mode. So, it'd make sense to add them into the UNSC roles. This would at least give the UNSC some buffer in terms of lagging behind compared to covvies already. So, a three role open at round start could work to at least give an edge the UNSC needs to stay relavent in this arms race right now. Though the thing is this role would need to be disciplined in a higher regard compared to ODST.

**Comment by mrturkeytoe** [comment]
I've also thought about this and it would be cool if they were in with say, 2-3 slots MK4 armor and ONI had to make them MK5 shielded armor and the slots had a separate whitelist from ODST that is instated once there's actually a handful of names on the list. I think UNSC will be a bit better off with the HA aswell though, and with fluctuating relatively low pop numbers it's of course hard to balance stuff appropriately. Also maybe give marines a couple more BRs available to regular marines when you increase the SRS availability so they stand a bit of a better chance against leets?

**Comment by PantasTheDank** [comment]
I completly agree with this.
The covenant is very strong at the moment, it would only be logical if the other sides would get some new roles such as a spartan.
The covenant already has a Shipmaster whitelist.
It would make sense to add Spartan whitelist in the similar way covenant shipmaster has one.

**Comment by X0-11** [comment]
Agreed, a spartan role should be available. I'd propose that the CO/XO is provided with a code on-spawn that allows them to authenticate an unsealing of cryopods onboard the UNSC station, which would open up the spartan jobs.

**Comment by Stingray540** [comment]
I disagree with this in every way possible. 
The reason that the UNSC is lagging behind is -mostly- because of naval combat at this point, which makes sense lorewise - the HA will help with this, but as I last saw the fact that the covenant have TWO shielded and armed ships is the main factor. 

Ground combat has been offset by the fact that both ODSTs and commandos have DOUBLE the slots that elites do. Shipmasters only come into play when you board the Covenant ships, because they are honour-bound not to leave. 

The issue is that people don't want to play anymore once their snowflake characters are killed. Most rounds these slots aren't filled and I see what happens - an ODST, marine, or whatever dies and refuses to respawn. They sit and wait because they do not want to play anything other than their main. 

Spartans will not fix this issue. It will devalue them. Lorewise, there is no way that the UNSC would send a *stationed* team of Spartans to a middle of nowhere colony when the Harvest Campaign is in full swing. They will not be interesting to RP with. Even if we ignore that, adding more whitelisted and restricted roles only makes the issue *worse* for the average player. If you join a server and realise that the only chance you have of not dying in the first five minutes is to get some whitelisted role, that's incredibly discouraging. 

The way Spartans are currently implemented in FC is fine. The UNSC sends a fax during distress, and they'll get either ONISTs or Spartans at an admin's discretion, and are usually removed after their mission is complete. If this were a whitelisted slot at roundstart, or even with XO's suggestion of making the CO/XO have to allow them to spawn - what about the URF? What's to stop the Spartans doing what the elites do to the UNSC, to the URF?  XO's suggestion does not prevent this, because unless it's admin approved it can and will be used for petty or insignificant reasons - and if it IS admin approved... what's the point? We already spawn them in when needed.

Text wall over.

**Comment by caelaislinn** [comment]
Spartans will get added to Invasion when there is pop to balance them
