### ISSUE TITLE
Covvie abilities/more elite balance suggestions

### ISSUE THREAD

**Issue by mrturkeytoe** [HaloSpaceStation/HaloSpaceStation13#1266]
Building off of #1265's notion of elites being a bit OP over all and satisfying #1202 with a unique feature rather than mere statistical changes

-Ruutian Kig-Yar get a 'Roll' with short range, basically a repurposed vox leap without the stun on a target to reposition

-T'vaoan Kig-Yar don't take damage falling through Z-level holes and get an ability to jump up through them. Maybe give it some hang time so they can jump fences too?

-Elite EVA shield mode gets removed once Ranger elites are in to better specialize individual roles so elites aren't just "I can do anything." Nerfing them overall while giving rangers a better reason to exist.

-Ranger Elites get jetpacks that give them a similar jump to the T'vaoan suggestion in gravity and immunity to fall damage with it breaking their fall as well as letting them maneuver unimpeded in gravity-less environment like vanilla SS13 jetpacks. Also lets them move up/down z-levels freely if holes are present while in 0g

**Comment by ghost** [comment]
I don't think the EVA shield mode should be removed. Rangers are implemented, they're EVA specialists. Their advantage is that they don't NEED EVA shield mode to operate in space.

Normal Elites have EVA shield mode because it is their "Softsuit". It reduces their shield health to a quarter, meaning it's remarkably easy to pop if they actually engage in combat. And while it's down, they'll start suffering from pressure damage.

Without the EVA shield mode any breach of any kind will murder elites. At the moment, if they have to use it, it means that they're going to be very vulnerable in combat. Far more so than they'd be normally.

**Comment by BDpuffy420** [comment]
Yeah EVA mode isn’t getting removed, since it’s the only “softsuit” for the elites, since the other races have EVA gear or natural EVA protection (grunts)

**Comment by X0-11** [comment]
I'd just like to note that elite EVA shieldmode is consistently active. Downing the shield does not cause pressure damage to start taking effect, afaik.
