### ISSUE TITLE
HA Elvator fuckd

### ISSUE THREAD

**Issue by CdrRiley** [HaloSpaceStation/HaloSpaceStation13#1306]
by using teh HA elvator its gonna space yer

**Comment by caelaislinn** [comment]
Mapping issue I believe, not a code bug

**Comment by Stingray540** [comment]
This is actually an issue caused by the implementation of Cael's new Multiz (I think). The old system read the z levels in the opposite order than the current system (at least for the HA), meaning that most of the elevators are not able to access levels due to their new ordering. If I'm correct, I'll just have to tweak the specific z-levels that each elevator refers to in order to fix them.
