### ISSUE TITLE
Incentivise ship to ship boarding

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#1398]
Currently most rounds seem to quickly turn into a space battle between the Covenant and the UNSC somewhere around KS7-Emsville. This ends inconclusively but frequently the Covenant ship seems to win. I'm not quite happy with where the ship destruction mechanics are at but other people seem to be ok with it (maybe it's just a HA problem being too tanky?). 

Some players have been complaining there has been very little ground combat recently because of this. 

Ideally if the combat happens near a planet and a ship is about to be destroyed, the crew can evacuate to the planet. Not sure if that's happening. Maybe players need more feedback when the ship superstructure gets low, or maybe space combat needs to be rebalanced? Again I think some of the issue comes back to the HA. 

There are two objectives for Covenant players to board human ships: retrieve nav chips and steal AI cores. I haven't seen those objectives carried out. Maybe players need more prompting?

**Comment by PantasTheDank** [comment]
Oh thats an easy answer, people tend to die before they can even reach the pods at all!
The covvies beams can cause explosions which I already stated are way too much of an overkill.
Even with HA the UNSC lost all the space battles that I witnessed or was a part of.
The thing is covvies get a point and click 100% to hit, traveling all the way trough the zlevel of the ship, causing explosions, making a good part of the deck without oxy with just a few barrages.
On the other hand the HA has deck guns,rockets and mac that have a travel time,which means the gunners need to calculate their shots,and lets be honest *most* (not all) unsc players have been lacking in both numbers and skill lately, they tend to miss a lot of their shots with HA ship weapons.
Speed and accuracy will always beat raw power.
And when the HA gets rekt the players trying to evac usually die from explosions and atmos while getting suits and running to pods.

**Comment by caelaislinn** [comment]
Yeah I'm thinking of nerfing Covenant pulse lasers (balance > lore). Another option is to place some of the escape pods into the middle of the ship (aimed "upwards" or "downwards") which will protect them better from bombardment.

**Comment by X0-11** [comment]
explosions on pulse lasers are a temporary measure until plasma torpedoes are implemented.
Boarding pods aren't used due to a lack of population a lot of the time, you need about 5 people to fully operate the HA, iirc. Boarding pulls those away from operating the ship/damage control.
HA's issue is incorrect weapon setup. All the weapons are linked to a single console instead of being spread across multiple local consoles which are then linked to a global control console. This has lead to the HA being inable to hit *anything* because of movement, covenant or not.

**Comment by caelaislinn** [comment]
With a crew size of 5, a boarding team of just 2 is a major threat while not (critically) compromising ship effectiveness. There should probably be a disadvantage for centrally controlling all gun consoles3

**Comment by X0-11** [comment]
There already is a downside to central weapons control, and said downside is also the main reason the HA fails to perform well in overmap combat at all. For ships with large amounts of weapons, central control makes it incredibly inflexible.

**Comment by ghost** [comment]
You have to also keep in mind that, at least with the HA, covvies approaching to close range at all is pretty much suicide due to the MAC. And there's no way to confirm if we've disabled their weapons, engines and whatnot. It's much easier to destroy the HA/force it to route, glass KS7, and go look for VT9 if the HA wasn't destroyed.

We also, to my knowledge, don't actually have boarding pods mapped in, so approaching to easily MAC'd range is the only option if the covenant want to board. This is, in my opinion, why the covenant hasn't been fulfilling the objectives of stealing the nav chip or AI.

**Comment by CdrRiley** [comment]
re view this
