### ISSUE TITLE
AMR size issues

### ISSUE THREAD

**Issue by Darkking1234** [HaloSpaceStation/HaloSpaceStation13#1413]
#### Description of issue

Title

#### Difference between expected and actual behavior

The AMR cannot fit in a backpack hence unable being able to be used while prone which has been confirmed by XO as a bug.

**Comment by Delnth** [comment]
If I recall correctly, the AMR is a Rifle. No Rifle would fit in a backpack. Otherwise we could have anyone carry billions of guns and ammo wherever they wanted. That's just my two cents. It just makes it easier to conceal guns.

**Comment by PantasTheDank** [comment]
XO said he was told to make all sniper rifles smaller so they can be used while prone
I'd say there should be a way to make snipers still as big as they are now and still allowing them to be used while prone,I too do not like seeing people put litteraly big guns in small backpacks because the game treats the sniper rifles size as if it was a pistol.

**Comment by X0-11** [comment]
should have been figzd
