### ISSUE TITLE
Covenant Balance Changes

### ISSUE THREAD

**Issue by Caelum464** [HaloSpaceStation/HaloSpaceStation13#1514]
#### Description of issue

Covenant are currently getting swamped and destroyed by overwhelming numbers due to the new population

#### Difference between expected and actual behavior

Usually, the Covenant and the UNSC are fairly even or one sided for the covenant (Which is techencally lore canon at this point). Right now, it's one sided for UNSC unless covenant play VERY sneakily.

#### Steps to reproduce 

Play Covenant. Die. Repeat.

#### Length of time in which bug has been known to occur
Since the pop was started growing

#### How to fix it (Multiple ideas)

Allow minors to be played unwhitelisted (Limited number), might encourage more people to play covenant at night while not screwing over the Majors.

Give grunts an extra respawn on the ship (To make them more swarmy)

Allow people to spawn as Hunters

Increase pain tolerance/shields on Shipmasters to allow them to defend better

Let T'Vaoan Kig-Yar duel wield Plasma Pistols

Put more weapons on the corvette for Covenant

Lock more doors on the Covenant Ship (Currently you can access just about anywhere from the umbilical) 

Let the shields cover the atmosphere of holes in the ship (No more sucked into space memes because shields randomly stopped supporting that one tile that got hit with a rocket!)

Increase accuracy of Covenant Weapons on direct clicks (Currently the miss to hit ratio is pretty wild compared to UNSC)

**Comment by ghost** [comment]
I disagree with having elite minors unwhitelisted, they're the backbone of the covenant since they're expected to serve an NCO type role, leading squads, enforcing covenant law and being fairly competent. It's already a pretty limited number role (with only 2), so I'd rather those slots not get taken up by randoms. 

Respawns can't be handled on a per species basis I belive, a suggestion for a 'Grunt Pod' (a deployable object which ghosts can spawn as grunts from) has been accepted and is in the dev cycle, to be added eventually.

Hunter spawns are on their way but there was an issue with implementing them

Increasing shields on shipmasters, kind of in the middle on this. Shipmasters are just renamed zealots, and they're fairly powerful as-is. If they're losing to less than 5-6 people rushing them, then it's a competency issue rather than a balance issue. 

T'vaoans being able to dual wield (it would let them dual wield any 1 handed weapon) doesn't really seem needed. They're not a CQC race, they're focused entirely on long range sniping combat, and they're really good at it. Their speed means they can rapidly redeploy between shots to avoid getting countersniped or brought down, and also move to better shot angles in a fraction of the time anyone else could. 

Weapons is more of a development problem at the moment, there's only a limited selection of covvie weapons implemented. Stuff like the plasma repeater, concussion rifle, etc still isn't here. That said, all covvies spawn with standard weapons (particularly elites with their plasma rifles) and with the recent plasma pistol buff, it's a very reliable main weapon.

Locking more doors to Covenant-only access would be rather nice

It would be nice to have shields cover destroyed floors but I'm not sure how possible that is.

Increased accuracy, I think the only weapon that might need a slight buff is the plasma pistol (from 1 to 2). Rapid fire weapons like the plasma rifle shouldn't have the additional accuracy, as they're meant for close combat. The needler is homing, all the long ranged weapons have scopes that massively increase accuracy when scoped, and the fuel rod gun doesn't really rely on accuracy to do its job.

**Comment by Nick123q23** [comment]
Sangheili Minors being such an important centerpiece for the Covenant to function is precisely why they need to be unwhitelisted. We already have majors and COs whitelisted to maintain a quality standard, Minors are the lowest rank any elite can hold and are essential to any covenant squad or lance, as otherwise they have no real NCO leaders on the ground.

If they are unwhitelisted, I'd also propose increasing elite minor slots, adding one or two for about four minors now that we have increased server population.

Devs already plan to add hunters and spartans with increased server pop

Shipmasters and zealots are fine, they just need to be more robust

Skirmishers aren't entirely snipers, refer to this 
https://www.halopedia.org/T%27vaoan#Role_in_the_Covenant
They're close quarters combatants who take advantage of their focus on speed in open environments.
That said, I don't think they need dual wielding.

Plasma pistols have already been buffed, covenant weapons seem to work fine so far.

Covenant IDs still need to be implemented

I also wish shields would cover the lower z level, but I'm not sure if the DAV map has one.

Rifles are more like an SMG and don't have as much accuracy by default. Longer rifles have scopes.

**Comment by Max-023** [comment]
To follow up on Bolter, currently shields do block floor breaches. However the method of doing this is to create a wall of shielding, making the floor unaccessible to repair unless the shields shut down.

As for Elites, I do not see the need to have them unwhitelisted. The current Elite Minors are fine as whitelisted roles. Their power as being a mini Spartan allows them to lead the charge of Covenant forces without having overwhelming numbers. If a role were to be added for the general public that used the Sangheili race, the only thing I can think of are Elite Minors that spawn without shields (much like how in Halo Wars 1 the Elites operated) but that is for balancing reasons. To explain their existence is beyond my knowledge of the Covenant, nor would it make sense as the Grunts and Jackals should be the main fighting force, not the Elites. The Elites are, in deed, the back bone of the Covenant military, but the Grunts, Jackals, Skirmmishers, Drones, Brutes, and Engineers are all the flesh, blood, and muscle of the military. You can give the Covies as much spine as you want, but if they don't have muscles to control, what is the point? I just don't see it happening.

**Comment by Nick123q23** [comment]
Elites have been nerfed before multiple times, a few minors shouldn't be game-ending anymore. The shield shouldn't be difficult to overwealm. My primary concern is that the covenant has no leadership whatsoever unless someone with a whitelist is online.

**Comment by Max-023** [comment]
The lack of shielding isn't necessarily for combating Marines. Rather it is so those with the whitelist not only get something better for whitelisting, but also can more easily control the unwhitelisted. The UNSC get an almost even split of very bad Marines and ok Marines. Sometimes the very bad Marines are just bad at combat, sometimes they don't respond to rank or command at all. This would just be to prevent the bad apples getting one of the most versatile roles the Covenant has and memeing with it.

**Comment by Stingray540** [comment]
The whitelist is a necessary evil to the fact that generally speaking the people in charge of the covenant have more power as a being. For example, if an elite is a god-awful leader, grunts still can't really physically do shit against them. If an XO/CO is being shit, they can be detained just as easily as anyone. Elites running around left and right would devalue them. I'd rather propose adding higher ranked grunts and kiggies than unwhitelisting elites.

**Comment by Nick123q23** [comment]
Grunt Majors can still organize unggoy, but the ruutian kig-yar still has no way to determine who's a major and who's a minor.

To my knowledge, all skirmishers are still whitelisted.

**Comment by X0-11** [comment]
A note: Ship shielding is currently capable of blocking breaches without blocking personnel, however, the ship's shield needs to be toggled to conform to the new ship shape.

**Comment by UntoldTactics** [comment]
Honestly, in my opinion what everyone said above is quite true when it comes to minors, we can't afford people having unwhitelisted minors running about, as they do act as an officer most of the time due to species, and indeed there's zero ways to tell a difference between major/minor as a kig-yar, however the shipmistress does get a energy cutlass.

Onto the Shipmaster, at this rate the Shipmasters is alone a lot of the time, any other sangheili probably deployed on a planet or otherwise, and a lot of the time they are swarmed by multiple marines, which would be okay to deal with if you had places to retreat to, but,  marines can go through most Covvie doors still, I'd advise giving covenant IDs or the sorts, so we can actually have all locked doors. Once I was swarmed two rounds in a row by at least double the marines compared to the entire covenant team of the round. (Which was around 7-8 marines - one with an RPG)  So yeah,  I'd highly recommend perhaps not direct buffs to shipmasters, but simply just making all the doors require covenant access.

**Comment by Nick123q23** [comment]
The shipmistress role should be removed, honestly. Nobody uses it and it's been rendered obsolete by the ship being led by Sangheili instead of the kig-yar missionary ship before.

**Comment by ghost** [comment]
Bump. At least could we get some additional locked doors, especially around vital areas like the engines/shield generator, bridge, armouries and umbilicals?

**Comment by caelaislinn** [comment]
That's easy enough to add. We could probably also add plasma turrets, we just need sprites for them

**Comment by ghost** [comment]
plasma turret sprites have been made for a while, if you mean the deployable HMG-type ones.

**Comment by caelaislinn** [comment]
#1646 is moving Covenant spawns back to their ship, and there'll be some stuff coming later on to help address faction imbalances (faction autobalance, low pop gamemodes etc)

**Comment by UntoldTactics** [comment]
This would work nicely, if we give the corvette a few more weapons (or just as is)  it will allow covenant to fight easier, I can say as a Shipmaster this would make life much more easier, allowing covenant to not need to shuttle around to find the corvette, and allows the forces to always stick close.
