### ISSUE TITLE
Deck Guns Suck

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#1537]
#### Description of issue
Deck guns currently are ass at anything but whittling down the shields of the SDV. Passed that they are inaccurate and slow as hell, without much justification.

#### Difference between expected and actual behavior
Compared to pulse lasers, deck guns are a laughing stock. While deck guns are better as point defense, there are no fighters or missiles capable of being intercepted. Pulse lasers are a guaranteed hole per beam and are super accurate. Not only that, but pulse lasers can vent multiple rooms and sections of ships with only 1 hit. Despite popular belief of the covenant, but their lasers are good. They have the capability of venting both medbays of the Bertels in 1 hit, no amount of armor stopping them.  Deck guns on the other hand just have the potential if turning 1 or 2 armor tiles dirty. They don't do anything and just exist to take up space for more missiles.

#### Steps to reproduce 
Play UNSC Bridge Crew. Shoot the deck guns. Barely hit shit and do nothing to what you do hit. Get critted out of your chair by a pulse laser. Repeat.

#### Specific information for locating

There is a console in the bridge, battle bridge, and the three towers.

#### Length of time in which bug has been known to occur

The entire round.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Caelum464** [comment]
I'd rather all weapons get longer CDs and more damage to better simulate long term ship to ship combat. Right now the game is structured around quick, instant gratification combat that is very boring and predictable due to the speed of overmap ships. 

I also thing the super structure of ships needs to be lowered significantly and the spawns of where rounds go needs to be upped for UNSC weapons hitting the corvette. It's okay if the ship goes red alert and people have 10 minutes to escape the craft.

It's not to okay to be the Dawson's Christian in a ship with more holes then swisscheese after 2 minutes of combat.

**Comment by X0-11** [comment]
Making ship combat last even longer is just going to bore people.
I do agree that the deck guns need a buff though.
Projectile spawns against the SDV have been recently fixed.
