### ISSUE TITLE
[Suggestion]Make Biofoam have a paradoxical effect on covies

### ISSUE THREAD

**Issue by Desolane** [HaloSpaceStation/HaloSpaceStation13#1594]
Covies tend to haul around a chemical designed by humans for humans and use it to heal themselves. Either make it kill them, do nothing, or place in an alternative specific to their races.

**Comment by Nick123q23** [comment]
I've advocated for replacing the Covenant's use of Biofoam with Sealant Mesh https://www.halopedia.org/Sealant_mesh
It's not really described as a chemical, more of a patch that does about the same thing.

I discussed this with someone from the dev team and they said the reason they don't have covenant biofoam is because duplicate recipes wouldn't work, apparently.

**Comment by X0-11** [comment]
This is essentially just "Resprite biofoam". This isn't going to happen, biofoam is an integral part to the combat loop due to it acting as essentially an "annoying shit" remover.
