### ISSUE TITLE
Spec Ops Rebalancing

### ISSUE THREAD

**Issue by Caelum464** [HaloSpaceStation/HaloSpaceStation13#1607]
Spec Ops Balance Suggestions:

Currently, Spec Ops Elites and Grunts by extension are not allowed in invasion. I'd like to see this change. Currently they are on par, if not far stronger then even the rare Ultras, which means they can't be spawned in most rounds, save for adminbus. 

I think we can change that, and give the three people who white listed as Spec-Ops a chance to play their whitelisted roles outside of the once a year canon rounds.

Idea 1: Make cloak more visible/give the cloak a timer like the Arbiters from Halo 2/3. This way, near invisible elites/grunts walking down pathways will no longer be a problem. They still retain their ability to have strong weapons and a decently strong skill in the right circumstances, but are slightly more noticeable.

Idea 2: Remove the shields, leave the cloak. Now, people can spray in the dark and if they get some hits on the Elite/Grunt, they actually go down instead of just regenning their tiny shields (This is also in canon that some spec ops didn't have shields.)

Idea 3: Remove the cloak. Spec Ops act more like ODST at this point, with a more varied and valuable weapon loadout and Minor/Major level shields. Perhaps give them their swords back, a full armory selection, and maybe a special gun they'd get (Or they could pass out if they didn't want it?). Now people can still play their black elites, but they no longer have to worry about people getting angry over them existing.

Just some spare ideas. Honestly, I think this could be done.

**Comment by Stingray540** [comment]
> Currently they are on par, if not far stronger then even the rare Ultras

No. Just no. They have 1/3 of the shields of Ultras and are vastly inferior to even elite minors in frontline combat. Their only advantage in combat is the potential for an ambush. See:

![dreammaker_2019-06-06_11-55-14](https://user-images.githubusercontent.com/4140319/59028265-0d669300-8853-11e9-8395-21323ba038dc.png)

and...

![dreammaker_2019-06-06_11-55-00](https://user-images.githubusercontent.com/4140319/59028281-18212800-8853-11e9-8ab5-0db51eddf053.png)

> give the three people who white listed as Spec-Ops a chance to play their whitelisted roles outside of the once a year canon rounds.

After a thorough search of the forums, I found one person who "applied" for grunt spec-ops, and none for elite. I'm not saying there aren't any, but please consider how Shipmaster, Honour Guard, URFC **and** ODSTs have _customised_ whitelists for their special role. How it works right now for the covenant minus the two I mentioned above, applying for anything gets you everything. What you put in the application is more of an RP thing for the forums rather than the role you want (Whereas the special roles mentioned have **individual** whitelists that are specifically named. There is no such thing for spec ops).

In regards to your third idea; sure, let's make them entirely useless since they have 50 shields. Make whitelisted roles prove that they're worthy by merit of robustness rather than having stronger gear than the others in the faction.

**Comment by caelaislinn** [comment]
This isn't going to happen re the current discussions about pop and job imbalance. It makes sense that Cov get a special units whitelist comparable to ODST and URFC, but both of those are already problematic with aforesaid pop and pop distribution across jobs. Particularly as Cov right now have the most jobs by far (13 vs UNSC 9 and Innies 4)
