### ISSUE TITLE
Covenant Ship needs IDs and Access Locks or Door Bolters.

### ISSUE THREAD

**Issue by Nightspark43** [HaloSpaceStation/HaloSpaceStation13#1621]
#### Description of issue
The Covenant Ship needs either ways to lock doors without hacking, or an ID system so they can keep important areas safe and secure, for example, the Slipspace Bomb, anyone, regardless of access, species, affiliation, anything, can come aboard the ship, and if there is not someone patrolling every moment possible, they are capable of simply walking into the bomb room, activating it, and strolling out to a pod or umbilical to completely remove the Covenant's combat capabilities for the remainder of the round.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by DexterDude** [comment]
Yeah, I think it's about time we finally got IDs, it can be pretty troublesome when some menial enters the slipspace bomb and blows up our entire ship on accident (or as an act of grief). I could see about coding this, possibly, would be a better way to learn how to PR than PRing a map I would think.

**Comment by caelaislinn** [comment]
We have a stopgap with species locked doors. All sensitive areas on the corvette should be mapped in with a species lock.

**Comment by DexterDude** [comment]
That's not what they are saying Cael, they are saying we need a species stopgap on doors, not faction. So Unggoy don't go into the Sangheili armory and so Unggoy don't go into the slipspace core.

**Comment by Nightspark43** [comment]
That and a lone human can't wander the ship unimpeded when the ground force leaves two people on the bridge, letting them 'wander' to the A-M bomb then immediately turn it on then 'wander' to an escape pod in roughly 45 seconds.

**Comment by X0-11** [comment]
That sounds like a mapping issue with incorrectly set secure doors. A majority of the doors should be secure, with only a few being open movement.

**Comment by DexterDude** [comment]
🗿 

The mapping isn't a problem, it's not having functional IDs. Any stuck up joe can shoot an unggoy in the forehead, take their corpse, slap them against the A-M door and blow us up (even though using the A-M is against the rules as human unless ahelping, so they use the slipspace instead.)

It's so you don't get instant all access right after killing an unggoy. It's not a mapping issue, as I have made all "high security" doors covenant secure, such as the antimatter and the supermatter. Unggoy also like to steal Sangheili gear, and that should not be the case, it can be easily fixed by giving us IDs. Not even requiring to be ranked IDs.

All we really need are Unggoy Minor & Major & Ultra as one ID, Deacon as another, Kig-Yar and Kig-Yar major as two separate IDs, T'vaoans would get the one labeled Kig-Yar (no minor) and so would the Kig-Yar Minor. Sangheili Minor-Ultra get the same ID, Shipmaster gets a separate one.

**Comment by X0-11** [comment]
That's sorta the point of asymmetry

**Comment by DexterDude** [comment]
they should get different IDs

**Comment by X0-11** [comment]
Covenant are different in the regards of access. You don't see elites carrying IDs around with them

**Comment by DexterDude** [comment]
They are not in game. They all have the same access.

**Comment by X0-11** [comment]
You miss the point, you don't pick up an elite ID during Truth and Reconciliation. The covenant just have different methods of access restricitions, mostly fear. If unggoy are stealing elite gear, that's an issue to be ahelped.

**Comment by DexterDude** [comment]
lore =/= gameplay

**Comment by DexterDude** [comment]
You can't instill fear in a player who is intent on being a retard, XO.

**Comment by X0-11** [comment]
Then you remove them because they're not playing the role and the species properly?

**Comment by DexterDude** [comment]
then they respawn. I'm just going to be honest here, it feels like you are trying to avoid coding this in. Why are you relying on administration when you can just add a gameplay feature to stop trolls and morons.

**Comment by X0-11** [comment]
It's incredibly easy to move the species lock into a by-door variable list and then allow that to be modified for each door.

**Comment by DexterDude** [comment]
then why do you not want to do it

**Comment by X0-11** [comment]
I don't want to implement IDs because they remove the asymmetry the covenant have in access.

**Comment by Max-023** [comment]
To be fair, the UNSC has their fair share of retards. We have ID locks, but that doesn't mean we don't have people hacking doors. The IWO's office has two ID locked window doors as well as an ID locked airlock door. Yet we still see Marines hacking the door to get inside. ID locks are not end all be all and if you have someone persistent enough, they will break into anything to get what they want.

Hell, the lockers in the IWO office are ID locked, but that doesn't mean you can't break them to get the items inside. ID locking everything means the thieves have to use an extra brain cell, not surrender because the door blinks red.


The only thing I would say that would work is to access the concerns and come up with individual solutions for each case, rather than trying to address it all at once, since griefing takes many forms and is much more intricate than you would believe.

**Comment by DexterDude** [comment]
Pretty much everyone in the Covenant wants the IDs simply because the system of everyone having all access to each and every thing. It's quite unfair when you compare us to the UNSC, who have every single door locked to different IDs, while we have to find a specific ID, they just have to find a dead unggoy who got 1shot and throw them against the door. This requires no thought at all.

**Comment by DexterDude** [comment]
And yes, I know Max, I just want this as an added safety measure to stop people who click on the Slipspace Drive with harm intent on on accident, not knowing it'll blow us up.

**Comment by X0-11** [comment]
That's just people not noticing the bright red text stating the fact they're priming it for detonation.
Being stupid isn't species locked.
And the difference between covenant and UNSC access is fukken intended, although obviously as I suggested a further granularity could be added to the species lock

**Comment by Nightspark43** [comment]
And I want this to make sure Humans don't have free reign of the Infraction, I'm fairly sure the Brig Is useless cause they can just walk through the doors, ruining the RP from the situation, and then they, or any other person who gets aboard can just walk right to the Core or Bomb and set it off, eliminating the covenant with little effort if there's only a small holding force aboard.

**Comment by X0-11** [comment]
A more granular species lock on the doors would achieve such a goal.

**Comment by Max-023** [comment]
Exactly. Locking it to a species means that you don't easily get access to stuff and people are required to lug around the body of whatever species ia required, this making killing or capturing more useful.

And the Bertels only has select rooms ID locked. The rest are open to everyone. And because the UNSC and URF are all one species, we are required to ID lock. Because the Covenant are all separate species with a clear hierarchy, locking some doors to that species would be sufficient.




Also, our slipspace drive is as exposed as yours. Any Marine can harm intent it. Making ID locks wouldn't fix this. You would need a species lock, but even then that would means some roles are required for you guys to function.

**Comment by DexterDude** [comment]
this is fine

**Comment by Nightspark43** [comment]
Unless you lock the Slipspace AND bridge behind Sangheili, things should be fine, and it would also mean any sealthers either need to hack through, which takes time, or get into potentially risky combat to get to important places.

**Comment by BDpuffy420** [comment]
we have ids sprited but this issue has been sorted through other means
