### ISSUE TITLE
[SUGG] Spirit of Fire

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#1785]
Allow UNSC personnel (preferably command roles only, such as XO/CO) to call in orbital drops using a console that establishes contact with the Spirit of Fire; unlocking various options to turn the tide of a battle or merely give some assistance to ground forces.

The console would have 2-3 options/programs:
- Resource manager (show how many resource points are left as well as a list of things that can be exported/imported with the resource income/cost)
- A map of the currently orbited planet so that a rally point/beacon can be placed (invisible, but visible on the map of the console, which allows the personnel to designate a specific area for the drop)
- Orbital deployments: ODST drops (up to five units), Spartan drop (only one spartan), various vehicle deployments (warthog, scorpion, etc), misc services such as materials, ammo, etc. Anything goes as long as it's just additional supplies that the UNSC already owns. There could be more infantry deployment options such as the hellbringers.

The Spirit of Fire system would work similarly to the WIP quest system, except that it is more akin to the basic SS13 cargo mechanics. Resource points would slowly increase every seconds, each drops would cost an amount of those resource points. However each drop would have a timer in order to avoid having an army of spartans suddenly appearing out of nowhere.

The possibility of unlocking and calling special units as reinforcements (like hellbringers) aims to provide additional support, but in the end, whichever unit is requested, they remain quite situational and their usefulness really depends on the situation. Making the right decision should take consideration, which fits to the role of a command officer. It also gives dead players a chance to come back, should they want to. 

Also I firmly believe that farming resource points should take a minimum of dedication, the more players contribute, the more points would be received and thus, more reinforcements can be called. There would be no limit to how many drops can be called, as long as the conditions are met (the only condition is to have the necessary points to buy the deployment)

**Comment by Max-023** [comment]
I'd rather call it a Phoenix system and whenever a ship is referenced, call it something like "Not One Step Back" or "Hailstorm" to avoid meshing with the canon, as lore is pretty much not something that exists here and anything referencing it would just feel forced and contrived, especially since there is no actual reason for calling the ship the Spirit Of Fire.

**Comment by Delnth** [comment]
As I said on the discord:

I don't see the need to discuss the name. I wonder why it even came up to begin with.
Spirit of Fire was used as a reference rather than a name suggestion.
It's better to refer to it as Spirit of Fire than "weird console that does X and Y shit". Being vague doesn't really help construct an idea.

Seeing how controversial of a topic it is and how lore fanatics seem to get triggered by it, I'd rather we skip the name discussions entirely, at least until this suggestion is considered.

**Comment by Chambers0** [comment]
Lore Nazi here
I like the idea
But due to the setting we're in (as in we're just a patrol unit) I feel that this ship would have no purpose being in the backline, rather than the front.
The UNSC is using every scrap of resources they have for the Human-Covenant war, why would they want their ship that acts like a mobile base not to help the marines in the front, it's the reason why they gave us a corvette rather than frigate, were just a patrol unit, we shouldn't need that much to defend a sector and warn UNSC Highcomm of mass incoming threat of Covenant vessels.
What we could do is use this ship for Special/Cannon Event so we can have a proper reason to have such a ship with resources and abilities.
But that's just my 2 cents

**Comment by Delnth** [comment]
> The UNSC is using every scrap of resources they have for the Human-Covenant war, why would they want their ship that acts like a mobile base not to help the marines in the front, it's the reason why they gave us a corvette rather than frigate, were just a patrol unit, we shouldn't need that much to defend a sector and warn UNSC Highcomm of mass incoming threat of Covenant vessels.

Sometimes, we shouldn't ask ourselves questions. This is a suggestion for a mechanic/system to match the one of the URF. This way, the UNSC isn't left behind with nothing to do (and certainly not waiting for the URF to farm money and equipment).

This is also the best alternative I can think of that does not involve admins interfering with the round/ERTs magically appearing. This is a solution to offer the players the possibility to control the events that occur within the round. There doesn't need to be wall of text to explain the ins and outs of everything, because otherwise it gets restrictive, unnecessarily complicated, and people will either starting pointing fingers whenever someone does not abide to whatever system is in place.

Faxing HIGHCOM is good. It promotes roleplay. But it's an heavily combat oriented server, as such, it might be best if the players could rely on each other rather than the admins. That doesn't mean the admins will stop creating events.

> What we could do is use this ship for Special/Cannon Event so we can have a proper reason to have such a ship with resources and abilities.

I have never mentionned an actual ship. In fact, I have never mentionned about the actualy ship's presence. Because currently, it's supposed to "be there" but "not there" at the same time. As in, it's present, but you cannot see it nor interact with it. Why? So that it cannot be destroyed. Just like the URF quest system cannot be destroyed (outside of total faction wipeout, and if there is no UNSC/Ship left, nobody can use the "Spirit of Fire") Again, this is a way for the UNSC to keep fighting. However, I'd expect the cooldown on troop reinforcement to be really high, so that the players may actually value their lives instead of throwing themselves into the death pit mindlessly. But it'd have to be balanced with the price, of course.

As for your concerns about the reasons of the mobile base ship's presence within the sector, this is purely because this is where the gameplay takes place, as such we are focusing on this sector rather than what may be happening somewhere else in the universe.

**Comment by ghost** [comment]
The label doesn't particularly matter, I'm sure the UNSC will be able to pick a name for it themselves. It sounds like a good system that gives a mechanical base instead of relying entirely on staff for special reinforcements. The only thing I don't particularly like is potentially unlimited spartans, but so long as it's unfeasible to see more than two or three per round, I'd be happy with it.
