### ISSUE TITLE
[SUGG] Add advanced splints for covenant

### ISSUE THREAD

**Issue by UntoldTactics** [HaloSpaceStation/HaloSpaceStation13#1815]
Add advanced splints, which act as normal splints, with a few extra features.

Advanced splints are slightly harder to break (If you can even break them in the first place)
Advanced splints will prevent damage from moving whilst with a broken bone. (Splints probably already do this)
Main feature about 'advanced splints' would be the fact that after 5-10 minutes it can heal the broken bone on the limb it's been attached to.

Now some might go 'oooh OP' but when you realize that the UNSC starts off with a LOT of biofoam syringes roundstart, I don't see a massive issue to it. Another thing might be adding this to the lifesaver huragok.

**Comment by X0-11** [comment]
why not just *add biofoam* to covvie stocks
or just some analogue to the unsc medkit

**Comment by UntoldTactics** [comment]
> why not just _add biofoam_ to covvie stocks
> or just some analogue to the unsc medkit

Cause any time we suggest adding biofoam to stocks the UNSC whine like babies, or even anything similar to adding stocks of chems.

**Comment by X0-11** [comment]
there's just no sprite for a covvie medkit, iirc

**Comment by Max-023** [comment]
Not a fan of the idea. That means Covenant will have less of a reason to fall all the way back to heal.

And while yes, you can say "but biofoam" but biofoam is used to counter the fact that Marine armor is ass and even worse when fighting the Covenant. They could also use pills and kits, but that would take longer to do.

I do agree, Ruutians and Unggoy get fucked over easily, but Sangheili and T'Vaoans could abuse the fuck out of this. Sangheili are tanky enough as is. Maybe if the Ruutians had access to "heretical medicine" that acted like biofoam, things would get better for the lower classes.

**Comment by Delnth** [comment]
This idea is actually balanced. Biofoam effect is instant, whereas this "advanced" splint would take way longer to fully heal the bone. I'd say that if their leg/foot is broken and they cannot walk, this splint could allow them to walk again at the cost of movement speed while their bone is healing. 

Whether they use this advanced splint or biofoam, the effect is the same; their application however, is different. We should shutdown an idea just because "they could be abused" or "hurr durr covie gear 2 op". Biofoam is OP. And the UNSC has it. Covenant must produce it or resort to surgery, since they can only carry one syringe/pill at a time. I seriously doubt a covenant splint that takes 5-10 minute to heal the wound would throw the balance out of the window. Especially if it only fixes the bone, and not the internal bleeding.

If they need, chances are it'd only be to stabilize them or allow them to retreat safely.

**Comment by X0-11** [comment]
biofoam / combat med kits have been added to covenant medical areas, issue resolved.
