### ISSUE TITLE
Give unggoy a "Don't act like an idiot" message on spawn

### ISSUE THREAD

**Issue by Sgtwok** [HaloSpaceStation/HaloSpaceStation13#1830]
Given how often Unggoy act like they are actual braindead morons, I'm proposing that, upon spawn, they are given the message that unggoy aren't two IQ children. More often than not our unggoy are either a UNSC main memeing or an URF main memeing. 

I cannot begin to list how many times unggoy speak with such original speech patterns as "ME SHOOTS PLASMA PISTOLS AT HERETICESES". This is infuriating, and can cause actual issues when people automatically assume they don't even know how a plasma pistol fires.

**Comment by ghost** [comment]
Grunts being LRP and memey, aside from being canon and enjoyable to play as with very little responsibilities, seems to help provide an outlet for meme behaviour. 

While I understand where it's coming from, quite frankly I don't feel that this is an issue. If they're making overt OOC jokes in IC, then that's what ahelps are for. Otherwise, grunts should be allowed to be memey.

**Comment by Stingray540** [comment]
Honestly, I feel this is more of an admin issue than a dev issue for github. Besides, our rules already state that you should maintain a reasonable RP standard, and I very much doubt that a start message saying "Don't be an idiot" is going to stop anyone if the server rules don't.
