### ISSUE TITLE
Huragok Spawning When Round Begins Is Breaking

### ISSUE THREAD

**Issue by Elzenio** [HaloSpaceStation/HaloSpaceStation13#2149]
#### Description of issue
It seems that whenever a round initially begins and people have the Huragok role selected and readied for, it breaks, keeping them in the lobby and not spawning any Huragok, while also filling the slot, thus making it possible for only one or no Huragok to exist in the round.

#### Difference between expected and actual behavior
Expected: Huragok spawns without issue. Probably dies later in the round via execution.

Actual: Huragok does not spawn but still takes up the role slot.

#### Steps to reproduce 
Step 1: Join server before round begins.
Step 2: Ready up with Huragok role.
Step 3: Wait for round to begin.
Step 4: Get frustrated and confused after round begins and you're still in lobby, no Huragok role existing anymore.

#### Specific information for locating

Object/Mob Name: Huragok(?)
No message output.

#### Length of time in which bug has been known to occur

Somewhere since January 10th.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 562d3bcdf2e19998bb192ed4e767bf904547e871 - alpha - 
Game ID: b5p-dLzH

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Real-MAGNUM** [comment]
This happens when Outer Colonies vote succeeds, but fails to launch while you are readied up due to lack of readied players. If less than 16 players are readied up when the outer colony gamemode launches and fails due to lack of readied players, all role slots that someone is readied up as will be considered **occupied**. An admin needs to open an extra slot for how ever many people were readied up when the vote failed to get the slots back. 

1. 2 Elite majors, 2 huragok, and 1 murmillo are readied up while waiting for Outer colonies.
2. The vote fails while they are readied up,
3. Reclamation starts, none of them are placed in the game.
4. Job slots show as: 1 taken elite major slots, 0 active. 2 Huragoks, 0 active, _(invis cause the role is filled to capacity)_ 1 murmillo, 0 active.
