### ISSUE TITLE
[Suggestion] Beam rifle fires too fast for it's magcap.

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#2179]
The beam rifle shoots way too quickly for its mag size and penetrative abilities. I wish we'd make it less spammy because even though it's supposed to overheat, it doesn't stop the covenant players from dishing out 3+ shots towards a single person in the span of a few seconds.

**Comment by WilliamWestmoreland** [comment]
I +1 to this issue its magazine capacity allows it to be spammed Its kinda overkill the damage can stay the same and the capacity itself but since it has a higher capacity a delay could be nice to implement to counter this issue with the spam.

**Comment by CommodoSix** [comment]
I disagree. The inherent overheat mechanic already negates the ability to spam severeal shots at once. Unlike its counterpart the SRS, which can be used as a ghetto shotgun to CQC due to the fact that it has no inbuilt mechanic to stop it from being spammed. Additionally the beam rifle deals less damage compared to the SRS, so any further nerf to it would make it far less viable than its counterpart.

**Comment by WilliamWestmoreland** [comment]
> I disagree. The inherent overheat mechanic already negates the ability to spam severeal shots at once. Unlike its counterpart the SRS, which can be used as a ghetto shotgun to CQC due to the fact that it has no inbuilt mechanic to stop it from being spammed. Additionally the beam rifle deals less damage compared to the SRS, so any further nerf to it would make it far less viable than its counterpart.

You clearly havent seen the changes to the SRS it has a high chance of missing if not scoped in which makes it unviable unless you scope in that means if you try and shoot anyone at a close range you will most likley miss the beam rifle got the same nerf as the SRS not scoped in however since the beam rifle carrys more shots you could spam it and eventually 2-3 will hit which negates the changes that were made to it to make it an actual long range weapon currently the Beam Rifle is being used in CQC which isnt how a sniper rifle should be used.

**Comment by CommodoSix** [comment]
The beam rifle can not be reloaded on the spot (unlike the SRS) and therefore already puts it at a disadvantage that the SRS simply does not have. Where an SRS user can carry several clips and easily fabricate more, a beam rifle user has to make sure each shot counts and then retreat to recharge, giving them less staying power than their marine counterpart who can carry ammunition in their belt. 

In fact the weapon rack requirement and the overheat mechanic ensure that if there's more than one person going up against a beam rifle user, they can advance and eventually overwhelm/push back the sniper. Add to that possibility of losing access to a deployed weapons rack and you essentially have cut them off from using the beam rifle again until they return to the flagship. Which is unlikely to be possible during an ongoing siege, since the orbit is usually either being contested by enemy ships or the flagship is too far away to even receive any requests for supplies.

**Comment by X0-11** [comment]
I'll be moving the fire delay up to 1.25 seconds instead of 1 second. The overheat mechanic should also become a bit more prevelant now. Don't spam or you'll be in a bad spot.

**Comment by Real-MAGNUM** [comment]
> You clearly havent seen the changes to the SRS it has a high chance of missing if not scoped in which makes it unviable unless you scope in that means if you try and shoot anyone at a close range you will most likley miss the beam rifle got the same nerf as the SRS not scoped in however since the beam rifle carrys more shots you could spam it and eventually 2-3 will hit which negates the changes that were made to it to make it an actual long range weapon currently the Beam Rifle is being used in CQC which isnt how a sniper rifle should be used.

Pretty sure Beam rifle got the exact same nerf to unscoped accuracy as the SRS, at the same time as well.

**Comment by X0-11** [comment]
Both snipers recieved the nerf.
