### ISSUE TITLE
[BUG/SUG] Flood

### ISSUE THREAD

**Issue by SuckMySocks** [HaloSpaceStation/HaloSpaceStation13#2244]
Description of issue:
Injecting yourself with the flood chem found in the Forerunner dungeons leads to you turning normally, however.

-Cannot interact with objects (crates and such because of mob type). 
-Cannot climb up/down ladders.
-Cannot pickup weapons.
-Cannot convert dead bodies by injecting flood chem (via punching), hit dead body 40+ times. Did not test on living.
-Cannot create infestor forms.

Difference between expected and actual behavior
You should be able to do all stated issues above.

Steps to reproduce:
Inject yourself with flood chem, attempt to reproduce above.

QoL Suggestions for Flood: 
-Allow Flood to interact with objects, I want to be able to hide in a crate and spook the shit out of unexpecting marines.
-Allow Flood Combat/Pure Forms to force-open doors, recommended 5-10sec timer.
-Make Flood Chem progressive, should not leave the body over time. If for whatever reason there is a Flood outbreak, it *should be hard* for players to put down. If you get hit that's your problem. 
-Make Antidexafen a counter to Flood Chem, slows down progression, slowly rids Flood chem from system, should not remove all Flood Chem from system, max bring it down to 1u.
-Give biomass counter for Infestor forms.
-Give Player forms ability to create biomass walls.

**Comment by X0-11** [comment]
Some flood forms are unable to pick up guns or create infestor forms due to them being modified for the Achlys gamemode. The weapons issue may also be linked to this.

QoL:
Object interaction is probably doable, probably.
Forcing open doors is the domain of infestors, not combat forms. Combat forms slice welds.
Floochem could be given a -ve metabolism, meaning it actually accumulates over time, however, this would probably be OP.
flood walls / floors / etc are *maybe* possible at some point, athough the flood really aren't a focus currently.

**Comment by X0-11** [comment]
Testing has revealed that on an unconscious but not dead body toxin injection occurs fine.
weapon pickup seems to function fine for the flood when done by the AI, but not by players.
