### ISSUE TITLE
[Suggestion/Balance] Multiple mostly covenant (specifically bird) QoL and balance suggestions

### ISSUE THREAD

**Issue by mrturkeytoe** [HaloSpaceStation/HaloSpaceStation13#2285]
1. Snipers should be armor slot compatible for everyone, not just spartans (SRS & beam rifle for parity)
2. T'vaoan champion should be a role in standard gameplay, humans have spartans, elites get SM/Ultra and brutes exist
3. Needler shrapnel embed gating from armor/shields PR makes them useless, I think it should be reverted or at least revisted.
4. Bird pain mod makes their speed bonus effectively null after considering the environments that combat occurs in more often than not and that the covenant are the attackers whereas the humans are defenders.
5. Bird hand armor is really flimsy.
6. Covenant medical belt can only hold specifically covenant medkits, it should be able to hold anything medical or chemistry related.
7. Covenant should have readily available backpacks and holsters at least and preferably should have bandoliers replaced with general purpose webbing.
8. Plasma weapons should have portable plasma batteries that you can carry on your person to refill akin to a magazine on the go.
9. Grenades should be able to go into belts perhaps.
10. To prevent grenade spam from covenant (and magazine spam from UNSC & covenant) introduce a variable storage capacity for bags where they can only hold x number of an item even if they still have space available. This would open up item selection flexibility by allowing players to put a wider variety of items into a wider variety of containers while still maintaining balance.
11. T'vaoans should be able to traverse z-levels without stairs if there is a hole in the z-level above them and jump over things like fences and leap onto second story roofs/balconies
12. Not sure on the range right now but Rhuutian eye-zoom should be brought to parity with the longest range zoom any weapon currently has if it isn't already greater. (so they stand to benefit more from using the beam rifle)
13. Rhuutian major role with a red gauntlet shield with additional health.
14. Better bird sprites.
15. Covenant have no wire for making grenades or more cable cuffs.
16. Covenant have no standard handcuffs and no 'purpleized' handcuff equivalent like gravity cuffs or something.
17. Through some manner of rejigging ONI should get a scorpion to counter the covenant corridor wraith strategies. Whether that's through taking one of the UNSC's or raising the factional tank limit to 3 I don't care.
18. M6D should operate like other automatic weapons.
19. Blamite cutlass feels kind of weak.
20. Spec-ops elites with either no shielding or shields worse than a minor's would be interesting. (Maybe spec-ops roles for other races aswell?)

**Comment by X0-11** [comment]
1: no, they're restricted for balance reasons.
2: adding more power roles is an iffy decision to make due to the already wide range of power roles available.
3,4,5: will investigate
6: intended, unsc ones suffer this too. to balance the fact you can hold full medkits in them, they're unable to hold other items.
7: no, they shouldn't their main downside is storage space.
8: no, their main upside is high magazine capacity + no reloading for the cost of overall capacity.
9: no, this was removed due to such a thing being too powerful. With buffed grenades, this would be even worse for balance.
10: no, that's not how the storage system works.
11: possible
12: the eye zoom is meant as a scouting tool, not a weapon firing tool due to the accuracy debuff incurred from long range firing
13: no, more power roles isn't needed
14: get a spriter on it
15: make a seperate issue
16: seperate issue
17: no, they don't need a tank, they have AT.
18: no, it shouldn't.
19: seperate issue
20: same issue with adding more power roles, seperate issue

Anything with a positive response should be placed in a seperate git issue
