### ISSUE TITLE
[Suggestion] Make Needler One-Handed

### ISSUE THREAD

**Issue by CommanderXor** [HaloSpaceStation/HaloSpaceStation13#2301]
### Description of issue
Quite simple, in both game and lore the Needler is used with one hand by most combatants. Unggoy use it one handed, Kig-Yar use it behind shields one handed.

For comparison the UNSC M7 can be fired with one hand and is quite effective.

Regardless I think the Needler should be altered to allow it to be fired with one hand/behind shields/etc.

**Comment by loafe** [comment]
Jackals with needlers would be VERY strong, needlers currently dumpster UNSC because they impale so easily, and that combined with the strong directional shield of the jackals would make them nearly impossible to kill otherwise

I am okay making it so grunts can throw grenades with the needler in hand as long as jackals can't use the needler.

**Comment by X0-11** [comment]
I'm afraid species locking it isn't going to happen. Jackals using needlers is supported by the games.

**Comment by Delnth** [comment]
Jackals with needler + shield are at a disadvantage. Once they are to reload, they are exposed, because they must deactivate their shield. Just know when to keep your distance, or when to put some pressure on an enemy.

**Comment by X0-11** [comment]
this actually happened finally
