### ISSUE TITLE
[Suggestion] Give Yanme'e Ultra and Leader GalComm (And maybe Jiralhanae Captain)

### ISSUE THREAD

**Issue by CommanderXor** [HaloSpaceStation/HaloSpaceStation13#2324]
#### Description of issue

All the current High Ranking Covenant members barring the Yanme'e and Jiralhanae get Galactic Common. To my knowledge it was decided that Galactic Common would be given to High Ranks.

Somehow both the Jiralhanae and Yanme'e slipped through this change.

Thus, I'd propose giving Jiralhanae Captain, Yanme'e Ultra and Yanme'e Leader the Heretic Assessment item on spawn.

**Comment by CommanderXor** [comment]
Yanme'e Ultra still lacks Galactic Common despite each Galactic Common speaking race having two of each slot, I'd like to ask that Ultra is also given Galactic Common, thanks.

**Comment by SuckMySocks** [comment]
From what I remember from the conversation we had in Devbus from months ago, when the devs were deciding on what Covie roles would get GalCom. We collab’d and came up with a list of roles that were considered acceptable and lore friendly. Most High Ranking roles were to get the ability to speak/understand GalCom, but not all. 

Yanme’e in lore *cant* even speak Sangheili. Lore wise the Prophets had to find *other ways to communicate with Yanme’e Queens* because their language is basically just loud screeching and pheromones.
It can be argued that  Yanme’e in game shouldn’t even be able to speak Sangheili, but for the sake of gameplay over lore, and ease of communication, here we are.
Giving them a more complicated language like English doesn’t make since, and didn’t really seem needed. 

However, I would totally be down for Leader to be able to understand GalCom, and if possible not have the ability to speak the language. Yanme’e are not a high ranking species, they essentially as mindless cannon fodder. Use the hive my dudes.

As for Jiralhanae - I honestly thought that Captain already had GalCom, so that was likely forgotten or glossed over when implementing, this is needed

On the topic of certain roles gaining the understanding of languages, I’d like to put forward Research Director, and maybe even Researcher gaining access to Sangheili language.

**Comment by BDpuffy420** [comment]
Lol no
