### ISSUE TITLE
[Suggestion] Defence Ideass

### ISSUE THREAD

**Issue by UwUPlusUwU** [HaloSpaceStation/HaloSpaceStation13#2327]
Title is very WIP.

ONI base really needs more defenses other than tank traps, tables, and barbed wire- as well as ways to bypass the 'one tile gap' rule in defenses.

Palisades
What: Pseudo-walls that can be fired out of if you're standing next to it, like tables.
Why: Tables don't look good ree.

Flippable Barricades

What: Like Plasteel Barricades from CM, but Halo-ified.
Why: It's so that you can make an entrance to your Hall of Nazis without sacrificing structural integrity.

Please send suggestions using the format.

![dornfortify](https://user-images.githubusercontent.com/47270986/77420333-6c09f700-6dfc-11ea-84a5-4aa0cdc4295d.jpg)

**Comment by Sgtwok** [comment]
I do not believe ONI needs more defense types, the fact you said "By pass the one tile gap rule" leads me to believe you are not acting in good faith.

That aside, having been on the attacking end on ONI defenses, when they build defenses, they are extremely effective, all without these flippable barricades and palisades.

**Comment by Delnth** [comment]
ONI base has narrow hallways, which gives an advantages to human weapons, especially those that have a lot of spread. There is not even a single alcove anywhere for opponents to take cover, which leaves them vulnerable to suppression and a zerg. (zerg = massive rush using all assets available)

Unlike CM, your opponents cannot plant weeds and regenerate their health off them. During an attack, there is absolutely no sustainability for your opponents. They are exposed most of the time not to mention the metric tons of doors they have to go through, which greatly slow their progress.

Although those ideas are good, they are not applicable in a defense scenario such as the ONI base, because it's often unfair for opponents to attack the ONI base as is. Making it harder will just make people want to skip VT9.

**Comment by caelaislinn** [comment]
New barricades and defensive structures added in #2424

**Comment by caelaislinn** [comment]
VT9 was removed in #2411 but UNSC players can make all the new defensive stuff as well
