### ISSUE TITLE
Firefight Stuff

### ISSUE THREAD

**Issue by SuckMySocks** [HaloSpaceStation/HaloSpaceStation13#2423]
Just a few suggestions and fixes for the Desert Outpost Firefight GM.

Firstly, I’d like to say that Firefight is a pretty neat concept, very enjoyable overall, but I feel like it’s missing a lot.

One of the things that I’d like to see changed is the map itself, as the desert outpost has been done to death. It’s to cramped and the moment that a single Unggoy gets into the centre of the box fort, it’s all over. Friendly fire becomes rampant because everyone is shooting inwards, usually resulting in a few friendly deaths. (This happened last test with 2 marines with SAW’s shooting inward, resulting in 3 marines being knocked out of the fight, this was also an issue with the flood gm)
Personally I’d like to see the firefight take place inside a blown out city setting, or military base. The makeshift half assed box fort in the middle of absolutely nowhere doesn’t do the GM Justice. 

Another issue is lack of materials and medical supplies. Not sure the exact amount of metal there is, but it’s not enough to lock down the area and properly attempt to dig in. From what i seen, marines had a hard time distributing the metal, resulting in 2 sides being sufficiently fortified, but leaving the other two completely without any proper defences - because they ran out of metal. Same issue with medkits, there’s only a handful between the 15-X players. One of the rounds the admins had to gift players an additional X medkits and combat medkits, but they ran out as well. Recommend maybe giving the players the ability to replenish their medical supplies, and properly tend to broken bones and other. 

 there’s no armor repair kits so marines are forced to fight with busted up armor.

Pretty sure there’s also no ammo boxes for the MA5B’s. 

There’s not enough flares to properly illuminate the area. 

Suggestions / Expansion

Something I’d like to see in Firefight is having all the heavy weapons removed from the startup. Heavy weapons/specials that do a ton of damage could be used as bonus items for when a wave is completed. 

Maybe add a supply ship that comes after every wave. With a supply console that allows for players to request things that are desperately needed like medical supplies, weapons and ammo, among some other things. 

Might add more, might not. Do with what you will with this.

**Comment by caelaislinn** [comment]
Great suggestions. Firefight is based off Stranded, which is what the desert outpost map was written for. Stranded was intended to be a wave defence/survival gamemode with elements of scavenging and base building. The big open map is partially thematic, but also more importantly a technical requirement due to the extremely dumb AI pathfinding which has unfortunately made a cool city map by Koen unusable until I rewrite the pathfinding. 

The gamemodes already have periodic supply drops. In the test I noticed they weren't spawning due to a mapping error, but I'm fixing that and I've set their frequency for at the end of every wave as well as round start and each drop will have construction mats. I'm tweaking the supply list, but when my changes go live the list of crates that could spawn in Firefight and Stranded (3-5 per drop) will be randomly chosen from the following list: 
- Basic guns (pistol, smg, assault rifle, shotgun)
- Advanced guns (br, dmr, lmg)
- Sniper
- Landmines
- Marine armour + armour patches
- Turret
- Medic supplies
- Misc (knife, flare, flashlight, frag grenades, armour patches)
- Tools
- Construction mats (steel, plasteel, and sometimes wood/cloth)

Crusade has a different Covenant themed supply crate list but otherwise the mechanics are the same. They have a weapon recharger rack and construction crate come with every supply drop. 

Doing proper pathfinding is on my todo list, but it's fallen to the back behind a lot of other projects. I might revisit it in maybe a month or few months unless there is a lot of demand for it.

**Comment by caelaislinn** [comment]
Addressed most of these in #2424
