### ISSUE TITLE
Nerf shrapnel

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#2465]
All UNSC weapons embed shrapnel which is a debilitating effect on players, unfairly impacting on their ability to participate in the round. As this originates from a RP focussed server (Bay12) whereas we have a focus on PvP/med RP, it's appropriate that we remove or nerf it. 

This would also make brutes more viable. For flavour reasons and to keep things interesting, I'm also considering leaving shrapnel enabled for shotgun pellets and brute weapon projectiles.

**Comment by X0-11** [comment]
shrapnel should still be a constant for projectile weapons, however I could understand if the damage from jostling it was lowered

**Comment by Max-023** [comment]
It isn't so much an issue with dealing with small amounts, rather it is because you can easily gather so much shrapnel that taking another step would be considered lethal. It negatively impacts lower armored roles such as the unggoy and brutes from the covenant and the colonists and innies. In fact, the issue is so bad for brutes that, as Eluxor puts it, you easily become a porcupine with how easy it is to akrue shrapnel, the overly large target, marginal armor, and slow speed making them super easy to shoot.

While yes, biofoam does remove shrapnel, it doesn't make the issue non-existent, and expecting everyone to lug around a bunch of biofoam at all times is just not realistic. We should definitely make shrapnel on the more rare side, lowering it's chance to embed drastically, so that the back end of combat is not just a mix of hellish punishments and god chems to override said punishments.

**Comment by X0-11** [comment]
this has been done by removing shrapnel's ability to embed even at full armour
