### ISSUE TITLE
Biofoam may be acting too much as a minor fix-all.

### ISSUE THREAD

**Issue by X0-11** [HaloSpaceStation/HaloSpaceStation13#2572]
As raised by @bloxgate

**Comment by bloxgate** [comment]
Going to take my message from #2571 and expand a bit on my reasoning:
>Biofoam is not and should not be a fixall. The fact that it is so close is the reason this OD problem exists in the first place.
>
> I would also argue that the buff we've made to OD actually makes involved medical knowledge more necessary as well. There is no non-surgical way to repair fully destroyed organs as far as I'm aware - and a large overdose is liable to do enough liver damage to cause the organ to fail. Rather than trying to rework biofoam to encourage the use of less powerful, but already present methods (peridaxon autoinjectors are readily available and specifically named in a way to indicate its purpose for treating organ damage) we've simply changed the game to immediately punish overdoses with death. Even if the immediate toxin damage doesn't kill you the lack of detailed medical knowledge when you inevitably kill an organ from the accumulated toxin damage will.
>
>This specific conversation may benefit a bit more from being moved into its own issue.
>
>Edit: Specifically I'd like to point out that biofoam does not repair dead organs, as it doesn't seem to undo the effects of the die() proc here which is in turn called here or when an infection reaches end stage.

I firmly believe that biofoam is too good of a fix all. Consistently I have seen relatively minor injuries been made much worse, simply because they were things that weren't fixable by biofoam. For example, prior to the buff to biofoam to fully repair all bleeding people would often never seek out further treatment for cut organs (resulting in their incapacitation/death) or would end up being severely injured by attempts at actual repair. Or, far more recently, incidences of fully necrotic limbs being reattached resulting in a quick death for the ~patient~ victim.

While I can understand that we don't want to have too many things that rely completely on surgery - as that is far too time consuming for how our combat is paced (and let's face it, we have basically no one that's both good and quick at surgery who's consistently online) - I don't think the solution is to have a single fix-all chem. The field medical kits with all of the autoinjectors are a good direction to go in IMO. Biofoam can stay as something that treats wounds, and assists with the healing of organs (or perhaps provide some level of anesthetic effect to help ignore some of the damage instead), while other chemicals with similar levels of availability are provided for more serious injuries.

We should also provide some more though to what happens when the players run out of biofoam and other medicines. We don't usually have too many people running chemistry, so a shortage of advanced medicines can and does happen occasionally. The more basic medicines that are readily available through simpler chemistry and the surplus of standard first aid kits both sides have disadvantages when it comes to the more serious injuries that both sides weapons are likely to cause. The UNSC's weapons can cause severe bleeding and embedding, while the Covenants cause burns and blood loss (to evaporation). Both of these are likely to cause the sort of injury that currently requires surgery or more involved medical attention once the advanced medicines are gone. To this end I think we may want to expand the autodoc a bit, it's internal surgery procedures are quite limited - it only fixes broken organs (quite magically I might add) and repairs minor organ damage. It won't do anything for someone that has a missing limb or an organ that has `ORGAN_DEAD` on in its status field. I'd always imagined the autodoc as something similar to the one in the second Rama novel, something that can do fairly complex medical procedures with little oversight from an actual surgeon. I could probably make an entire post on just what I'd like to change/expand with the autodoc, but that'll have to wait for after the hellbringers PR (soon^tm).

While I understand that these changes would negatively impact the few people that like playing medical, I think that opening up their role from tending solely to the complex injuries might open up some interesting avenues for play. The last time we ran an outbreak event, for instance, a large problem occurred as the entire medical staff had to focus on treating injuries rather than actually working virology. Freeing up such a large portion of medical may well make that a viable gamemode again.
