### ISSUE TITLE
On the issue of T'vaoans

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2611]
#### Description of issue
T'vaoans, as they stand, have far too many advantages over a marine due to their relatively low increased brute damage and their significantly higher speed. One of the main reasons that UNSC players have so many issues with T'vaoans is that they are not punished for their bad positioning, as they can just outrun everyone, even if they get cornered, and can tank a good number of shots. This leaves a lot of UNSC players frustrated, because a few minutes later the T'vaoan comes back with repaired armor and full health like they never got caught in the first place. 

T'vaoans have a significant ability to maneuver around marines, meaning they can constantly engage them at a distance, flank them, and do hit and runs. However, if they get caught, they should get punished, either by severe injury or outright dying. At the current time, that is not how it often goes, especially with the extra grace shot that a Murmillo gets. 

Because of this, I suggest one of two alternatives. One could be hollow bones, so if a T'vaoan gets caught they get a broken leg or other broken bone, significantly slowing them down and allowing the UNSC to run them down and finish them off if the T'vaoan goes in alone. A second alternative is increased brute damage (1.3-1.5x), which would likewise increase the rate at which bones break, but also make them die faster. 

Of the two, hollow bones make the most sense to me, as if the T'vaoan isn't engaging alone, they can fall back and get covered by their team. This encourages "squads" of Covenant rather than single engagements, giving the Covenant incentive to play as a team.

**Comment by X0-11** [comment]
I'd be happy to up their damage multiplier to 1.3. Hollow bones wouldn't have the same effect as what you think, as all they do is lower the threshold of damage-to-break-limb a slight amount. An upped damage threshold should raise the skill floor for t'vaons whilst still allowing them their speed.

**Comment by loafe** [comment]
That works for me. We will play it for a while, if it feels too powerful or too weak, we can reassess the situation.

**Comment by Sgtwok** [comment]
Heavily disagree with this issue considering how rare the t'vaoans are, only being two slots, and only one of them having shields.

Also considering that even the shielded t'voan isn't all that powerful thanks to SRS and Beam rifle shots outright ignoring shields that aren't handheld.

**Comment by Archi-guy** [comment]
I am not sure what kind of "not punished" OP means. T'vaoans are very much punished when they receive damage, this can be confirmed by pretty much every T'vaoan main (which the Covenant has like 1-2), and they take skill to avoid damage. Their bones, or just limbs in general quickly become messed up upon receiving damage from very few hits. Some guns can outright gib their limbs on hit. So, I don't support making T'vaoans even more fragile.

**Comment by 24THBN** [comment]
I feel like 1.3 would be too punishing, as it was their damage multiplier before the overall speed nerf to all specialized species, while I personally think that nerfing their armor instead (considering they are meant to be light to be more efficient mobile units.) that seems to be out of the question.

I feel that making them a bit slower to be easier to hit when caught would help, and would be less of a: ''If you commit a mistake, you outright die.'' solution like proposed.

I actually think that if the issue with their speed is so big, it should be toned down at least to Spartan tier, so they also have an actual unit that can keep up to them in foot (**Reminder that vehicles could easily catch up with Tvoans**) and providing a sort of ''counter'', it would also make UNSC want to play Spartan more, since most players don't bother most rounds, plus they also have the same number of slots as T'voans (Only two, Spartans can spawn at 1:30 round time and instantly after the ODP is destroyed), so Covvies would have also a speedy enemy to fight with.

Also a note: XO, don't feel forced to balance this because you already made preparations for the damage multiplier, I feel we could actually just delay this for when the next big patch settled even, but not just for that, but because we can actually discuss things to make more reasonable changes and not just complain in Discord.

**Comment by CommodoSeven** [comment]
I have to disagree as well. Upping the damage modifier even further will make the class even less player friendly than it already is. Keep in mind this git issue primarily stems from a single player being good at it after putting a lot of time into learning the class. Any new player who wants to give t'vaoan a shot will see them die to a single burst from a rifle and not touch them again.

Furthermore it is important to mention that counters against t'vaoan are already in place and have proven very effective at countering the class when those methods are actually being used.  Sniper rifles, armed vehicles that can outrun the t'vaoan, MP7 and spartans all make for excellent counters. The other factions unwillingness to utilise these means is the primary reason why that role can be so effective on the battlefield. 

Previous nerfs such as decreasing movement speed and making sniper rifles and the MP7 bypass shields further pushed the class into a tough spot, where bad positioning and not prepping meds ensures certain death. Since even now a single bullet that goes past the shield will significantly slow down the t'vaoan in question. Upping the brute modifier even further would make heavy hitting weapons such as the SRS able to possibly put a t'vaoan in crit in a single shot. Add to that the fact that most UNSC weapons can be very quickly fired or have a high damage output, such as the shotgun and magnum, and the class will be even worse off than it already is. I do not believe any class should be able to die in a single shot, it makes for a unrewarding experience for whoever killed them and not fun at all for the one who died.

The skill ceiling of playing well as a t'vaoan is already very high, since it includes a lot of prep work, split second decisions and good positioning to stay alive. Further nerfing the class will only make it much more tedious to play to such a degree that it might even be seen as not viable anymore to be played at all. Given the fact that there are other races that can pick up a sniper rifle and do just as well without any of the downsides that already come with picking murmillo or commando.

As Sgtwok already mentioned the class is also limited to two slots. The limit is set in place because a certain class is very powerful, like spartans for example, and as such should be rare but good at what it does. These new suggested changes go completely against that by making those two slots easier to kill than lets say a basic marine or unggoy, of which there are unlimited slots, which would contradict the very basis on which class limits are built upon.

**Comment by 24THBN** [comment]
I also think that T'voans should be used more in mid-range combat, previously, the thought of having a T'voan **ALWAYS** being a hit and run or sniping unit is because they did hate 1.3 damage multiplier, of which they suffered a lot, so going 1:1 against a marine was out of the question simply because you took more damage.

Making them return to said damage multiplier would make the current issue even more prominent, because they would also be more forced to do battle AWAY from everyone so they don't just get super injured instantly.

Remind yourself that before the overall speed nerf to all specialized species was active, T'voans still did the same hit and run and sniping only problem and XO tried to fix it many times to no avail until said update was made.

**Comment by X0-11** [comment]
Update: #2607 has integrated a change that places tvoans with a 1.25 brute/burn multiplier, and a 0.8 pain multiplier. This combinatin means that whilst more overall damage is inflicted, the pain recieved is the same.

**Comment by Glissery** [comment]
I'll hop in here too.

While I do think that you -should- be punished for being caught as what is essentially a "Run and gun"/"Hit and run" role, I don't think making the damage they take worse would really help the situation.

Now if they get shot and a bone breaks, yes, they should be severely slowed to encourage group combat, or at least having reinforcements nearby in case such situation arises.
But come on, most covenant species are being nerfed into the ground because the marines want to satisfy their K/D ratio but Yanme'e keep flying around and killing them, or something along those lines.
I can see a sort of pattern here.
UNSC whine on Git: Instant response and Covenant nerf, likely
Covenant whine on Git:. Response takes forever and it may not even be considered.

I'm sensing a bit of favoritism, Halo 3 vibes anyone?

**Comment by X0-11** [comment]
Please refrain from going off topic when commenting on a git issue. Changes are made as individual decisions based on multiple data points and not the nebulous ideal of bias, nor is every git issue created equally with relevant focus placed on the right parts.

**Comment by Sgtwok** [comment]
Gliss, that's not helping.

**Comment by Glissery** [comment]
There were four people saying no, and you did it anyway.
You obviously don't care what we think.

**Comment by X0-11** [comment]
Noted. This is not a democracy.

**Comment by Glissery** [comment]
Oh, noted.
I'll remember that, my opinion doesn't matter and I shouldn't bother giving input.

**Comment by X0-11** [comment]
I'm afraid that taking this attitude most certainly starts to devalue your opinion.

**Comment by X0-11** [comment]
A number of alternative ideas have been raised in this issue and the previous action has been reverted for now.

**Comment by loafe** [comment]
@Sgtwok: Yes, T'vaoans do only have two slots, this is true. This does not change the fact that considering their role, they are too strong. Skirmishers are meant to use their speed to position against the UNSC and flank them, not straight up tank shots. In terms of the SRS, every single T'vaoan I have seen (not just Rouley) carries a Beam Rifle, and in terms of sniper duels, it's an RNG roll, and the T'vaoan has the speed to outrun a marine if they start losing the sniper fight. 

@Archi-guy: According to the stats on the species page, T'vaoans take 1.1x brute damage, which is only 10% more than normal, meaning that an AR shot does 33 damage instead of 30. Also, they don't take pain damage from that due to a seperate modifier. So, their bones are only SLIGHTLY more likely to break on a given shot, and they can eat just about as many bullets as an average marine (which with full armor is 8-12 depending on RNG). Combined with their speed, this lets them get out of some sticky situations in which they get cornered where a marine (or any other class really) wouldn't be able to.  In terms of limbs getting gibbed, I cannot tell you how many times my hand or foot have been ashed by a plasma pistol or plasma rifle. Both sides have the ability to remove limbs. 

@24THBN: I don't necessarily disagree with your first post. Their speed is high, but that is kinda the point of the race: to flank and outmaneuver the UNSC while they are distracted with others. Since that is so crucial to their identity, I think it makes more sense for T'vaoans to have to rely on their positioning more than their armor or health. While I would be equally as happy with a speed nerf, that was taken off the table many moons ago through other discussions. 

Having Spartans be the only counter to a T'vaoan seems strange to me, considering that the Spartans are the only UNSC power unit, and generally can't get bogged down with chasing a single T'vaoan around while they have to stop the scanner. 

Likewise, I'm not suggesting that one mistake should result in death, instead I'm saying that if marines manage to actually corner a T'vaoan, which is the result of many mistakes by a T'vaoan, that they should die instead of being able to weasel out. One mistake would be running into a sniper's line of fire, and eating an SRS bullet or two, which wouldn't kill the T'vaoan, just fuck it up. 

In terms of vehicles, I have mentioned this before to XO, but vehicles have a somewhat hard time dealing with T'vaoans since Geminus has so many building to duck into, and when the marines go to corner it, it usually snakes out through sheer speed and being able to eat enough shots to get away. 

@CommodoSeven: This class is not about any player in particular, because I have noticed these issues with every T'vaoan player. 

T'vaoan armor has 4 grace shots, and they have essentially 200 health until they are down for the count. A MA5B burst is 5 shots, each dealing 33 damage to T'vaoans because of the brute modifier. Doing some quick math, it takes 7 MA5B shots to account for the 200 health, plus the 4 grace shots for 11. Assuming all bullets hit, that's three bursts, at an extremely fast moving target. I don't think that they are  weak by any means, as that is about what it takes to kill a marine depending on RNG. 

I can't speak for the offputting nature of the class, but I can't imagine that a new person would be scared to play it when they move so fast. I have played T'vaoan on Crusade, and it felt very smooth and easy to play. They were NPCs, but then again, NPCs aim better than players, so go figure.

The damage change would not have the T'vaoan die in 1 SRS shot. It would take 2 assuming RNG favors you, and it only takes 3 shots to kill a marine with a beam rifle (once again depending on RNG). Considering the ability of the T'vaoan to dip in and out of sniper range with ease, the T'vaoan will generally win a sniper fight against a marine with not much damage. Likewise, with the sniper changes coming up, snipers won't be as terrible to play against, so this will likely become a non issue.

The slot argument is perhaps the worse I've seen on this thread, because slot count does not indicate the strength of the unit. Unggoy Deacons get one slot, and are not gods. They are limited so there is some balance on the Covenant side. Comparing a T'vaoan to a Spartan is strange, considering the rarity of Spartans, the abundance of other Covenant power roles, and the fact that T'vaoans shouldn't be able to mano y mano a Spartan. 

I don't think that this change will add tedium to the T'vaoan, it will just force them to change their gameplay style. It will force them to think about flanking routes, and their movement rather than just "haha run up and brrrr" because they can eat a few shots before retreating and healing to full. If you don't want to play a class because it's fragile and has a high positioning factor, there are other Covenant classes that are more suited to you. 

@Glissery: I suggested hollow bones, and XO decided on more brute damage. I won't address the rest of your post with a response.  

**I am open to counterpoints.**

**Comment by Sgtwok** [comment]
It takes 4 beam rifle shots to properly down a marine, 2 beam rifle shots to kill a t'vaoan with the original proposed change, marines are also unlimited. 

One thing to take into very extreme note is how limited t'vaoans are compared to marines.

**Comment by loafe** [comment]
@Sgtwok Marines are unlimited, but SRSs are not, and the ammo is likewise limited, unlike the Beam Rifle. In terms of the number of shots to kill a marine, it depends on RNG, but 3 is the bare minimum.

Yes, there are only two T'vaoan slots, because they are not the primary force of the Covenant. Just like Spartans are super limited compared to brute minors or grunts.

**Comment by Sgtwok** [comment]
You literally have ammo fabricators. Plus it only takes one shot to immediately negate a t'vaoan's speed advantage. The only advantage they have over marines.

**Comment by loafe** [comment]
Yes, we have ammo fabs, but metal is used for things other than SRS ammo, and if I have to go mining to make SRS ammo, that is an issue. 

Likewise, T'vaoans have a speed advantage over Spartans as well. One shot from an SRS does not slow a T'vaoan assuming that their foot isn't blown off, which as such a range is a low chance.

**Comment by Sgtwok** [comment]
Loafe, pain causes t'vaoans to slow down.

It is not my problem, or my fault, if you cannot hit the t'vaoan. You have a multitude of methods to handle t'vaoans, including herding, vehicles, counter sniping, or just pure stubborness. What you are asking for is for the skill ceiling to be raised even higher for T'vaoans, and for marines to have an easier time. You have methods. Use them.

**Comment by Joe44445** [comment]
The main point of the post is not even the speed of the skirmishers being too high, it's the fact they are being cornerend (funnily enough, using those exact same methods you've described) and are still tanking shots and weasling their way out of getting cornered and not getting punished for stupid mistakes which is the main reason for this post.

**Comment by Sgtwok** [comment]
It's also not my problem or fault that a t'vaoan player has learned how to recover from mistakes.

**Comment by Joe44445** [comment]
did...did you actually read my post? I said they're making mistakes and getting cornered, which should very well be a death sentence for something that is meant to rely on positioning to win fights, and not being punished for making a bad call on that positioning. there is a difference between "recovering from mistakes" and getting cornered by a UNSC squad and still tanking shots and running away, which has happened to us in the past.

**Comment by Sgtwok** [comment]
Yes, because the player has played t'vaoan so much they've learned just how to recover from mistakes like that.

It's already an extremely high skill ceiling class, again, what you are demanding is asking for marines with less skill to be capable of taking on t'vaoans with more skill. 


Also they're probably just going ham on painkillers.

**Comment by CommodoSeven** [comment]
Your experience is limited to crusade. On a map that is wide open, with your teammates nearby and npcs being by no means as smart or coordinated as actual players. Basically the odds are stacked in your favour. Which makes for an incredibly skewed experience regarding what t'vaoan feels like when it comes to going up against actual players.

55 * 1.3 equals 65 damage. Two SRS shots suffice to put over 130 damage which will absolutely mess them up. Add to that the fact that more damage means quicker adrenalin OD and it gets even worse. So given the high speed fire rate of the SRS and the mag size, you can down both available slots in a single mag. Add to that the fact that even with the new pain reduction 2x55 will slow them down to such a degree that they can not possible respond in any other way than die (assuming they're not outright going into pain crit.) and you have have the perfect recipe for a terrible time for any t'vaoan player. 

Meanwhile the most basic marine continues to take up to four beam rifle shots and might not even go down after that assuming they pack a pill bottle of trama and dermalin. Add to that the fact that t'vaoan limbs already get gibbed with the current damage multiplier and it puts them in an even worse position where a single shot from a MA5B can take off a foot or a hand without much trouble. Now apply that to shotguns with their multi-hits or an SRS with its high damage and you'll see birds losing limbs left an right.

It does not make for a good player experience nor does it increase the skill ceiling. If anything it lowers the skill ceiling for the opposition because they are either unwilling or unable to adapt/get better.

**Comment by loafe** [comment]
@Sgtwok: I'm not demanding that at all. What I'm asking is that marines be able to kill a cornered T'vaoan. A high skill T'vaoan shouldn't be getting cornered in the first place. 

@CommodoSeven Yes, a wide open map. Just like Geminus. I admitted that I don't know how it feels to players, but from my limited experience, I can imagine that it would be easy to play as. 

In terms of the SRS: Yes, two shots from the SRS should mess you up, it's a 14.5mm bullet. And 3 shots will be the bare minimum to kill a marine, and likewise a T'vaoan. The fire rate of the SRS and beam rifle are the same. My point is that if a T'vaoan tries to get into a 1v1 fight with a marine sniper, they should have to position themselves to win, not just rely on RNG and their health. That is the entire point of the species. 

If limb removal becomes such a huge issue, I can even propose adding foot or hand armor so it doesn't happen. In my experience, I don't see it happen that often, at least not more often than marines losing limbs to plasma rifle/plasma pistols/beam rifles/carbines.  

As a few general points, I see this term "skill ceiling" getting thrown around, but it's a relatively loose term. I think that if T'vaoans had to rely on positioning more than health, it could raise the skill ceiling, so if you are really good, you can constantly flank the UNSC and make their life a living hell instead of just standing there and clicking their sprite with a beam rifle, and running away to patch armor and heal after getting shot with an SRS. 

As another point, I never mentioned snipers in my original post, as they will become far less "insta-fuck yous" after the update. I am referring to how T'vaoans can get cornered and still escape through a combination of their speed and pseudo-tankiness when no other race in the game could escape.

**Comment by CommodoSeven** [comment]
They are both snipers, movement is of no importance at that moment. Its about who gets the drop on the other. Only that this change will ensure that even if a t'vaoan manages to snipe first, they will still be at a disadvantage due to taking much more damage than their human counter part. A class that is so heavily focused around long range engagements should not be at a disadvantage. Mid- to close range is not possible either due to the amount of damage the role takes. So if they can't even hold their own during long range engagements, what purpose do they serve? None what so ever. 

The covenant roles are specialised to a degree where they excel at one thing and are garbage at other stuff. The t'vaoan role is the most affected by that design phylosophy. You mention it yourself that you primarily want to change that getting cornered will result in death, which is not something i am against. Unfortunately this change would make them terrible at long range engagements as well, which should not happen.

Right now the class is being shoehorned into being a sniper because their traits and stats leave them no other choice. The upcoming sniper change and the possible brute modifier increase essentially makes them no longer viable as long range fighters either. So unless what follows are changes that make them more viable for mid- to close range engagements, I firmly believe that this change is not good at all and will only further sour the experience for anybody playing t'vaoan.

**Comment by loafe** [comment]
Sniper battles do not boil down to who fires first. T'vaoans are ALWAYS able to disengage in a fight due to their speed, while if a marine tries to disengage they get chased down. 

T'vaoans are not long range specialists. They are supposed to have a hit and run playstyle, with whatever weapon that may be. One can use a T'vaoan as a sniper, but relying on its tankiness instead of its speed to be an effective sniper is counter intuitive to the point of the class. 

Your point of saying that the change would ruin the class is moot, it would just require a change in playstyle. As I said in the original post: T'vaoans should not be able to 1v1 a marine at close range, or even long range assuming they stay engaged the whole time. T'vaoans should use their speed to engage and disengage at the right times in hit and run attacks.

**Comment by Sgtwok** [comment]
The hit and run playstyle is literally suicide with the changes you are proposing.

Also how in the hell can you say "They are supposed to have a hit and run playstyle" and also say
"T'vaoans should not be able to 1v1 a marine at close range."

**Comment by loafe** [comment]
>  T'vaoans should not be able to 1v1 a marine at close range, or even long range **assuming they stay engaged the whole time.**

Hit and run does not mean they are engaged the whole time. It means you attack, and when they turn to shoot you, run the fuck away and flank them. 

I imagine that it would function like a runner from CM, like an annoyance of larger packs and being able to pick of solo marines.

**Comment by Sgtwok** [comment]
Again, this change you are suggesting makes it SUICIDE since they'd have to stay far away from the field anyway to avoid taking damage from shrapnel or stray shots, of which, the Commando especially has to worry about since they don't even have shields.

**Comment by Jaybirdyy** [comment]
I'd like to reply there.  The thing is, if the T'vaoan is hit once, there's a high chance that they won't be able to get away, even now.  Pain slows down movement speed, which means they will be hunted down anyway.

**Comment by loafe** [comment]
@Sgtwok It wouldn't be suicide. Ideally, the UNSC wouldn't even be able to shoot you before you moved off, but even if they do, it won't be enough gunfire to kill you. I'm not saying you run up to the pack and stab them twice with a Blamite dagger, I'm saying you use a needle rifle or needler and pop a few shots at the marine from distance, and fuck off to attack from somewhere else. 

@LordDoge A single shot from an SRS will not cripple a T'vaoan in a significant way assuming that they are full armor, assuming a limb doesn't get gibbed. Marines after getting shot with a beam rifle generally don't have movement issues until the second shot. Likewise, a biofoam syringe makes you move at full speed for a while assuming you aren't near crit.

**Comment by Sgtwok** [comment]
It literally would be suicide since unless they manage to find a corner, even a random shot hitting them would slow them down.

Four of your weapons have scopes, SRS, BR, DMR, Magnum.

Three of those, are almost always readily available.
One of which, almost every marine carries.

**Comment by Joe44445** [comment]
you do realise that even with these changes they would still have 4 grace shots, right?

**Comment by CommodoSeven** [comment]
At the current speed level that is not possible. If you would like to go for a more CM runner related route you would have to give them a speed that makes them adequate in disengaging unless confronted with a properly sized group that can focus fire. To achieve that three things would have to happen.

1. The proposed damage changes to make them as fragile as runners.
2. A higher speed in exchange. Previous t'vaoan levels of speed may be suitable.
3. The addition of plasma rifles to their armory to make them able to engage in mid- to close range combat.

**Comment by Jaybirdyy** [comment]
I apologize, but I don't quite understand the point of nerfing the T'vaoan.  As a new player, I have found it mighty difficult to play something like that, and it's definitely already a high skill ceiling.  I feel like this change will be alienating this race to the point of non-use, as it simply has no reason to play it anymore.  While I can't speak on more of a technical side as I have not had a lot of experience with halostation, but even now, it looks like there's no point in T'vaoan.  If you want them to be a hit and run, that's understandable, but by making them harder to be a hit and run seems a bit backwards to me.

Covenant is already a point of contention, and I don't quite know why we'd want to make it more so.  Just like how it takes skill to be a good T'vaoan, it should take at least a bit of skill to fight them.  Just like how fighting a marine can be tough, it all depends on skill.

**Comment by Sgtwok** [comment]
Doge made an excellent point, why should we have to learn an already limited role even more than we already have than a low skill infinite role that can easily dispatch a our own?

**Comment by loafe** [comment]
If you're suggesting leaving a race too strong just so people play it, that's... something else. 

T'vaoans have a -1 slowdown, so they are twice as fast as a marine, and a third faster than a Spartan. My point is that they could be very strong if played well, but they shouldn't be able to be twice as fast as marines and have nearly the same damage intake. To Commodo's point, all races in the Covenant generally have a downside. I am arguing that the T'vaoans downside, a 10% higher brute damage modifier is not high enough to justify their boons.

**Comment by Jaybirdyy** [comment]
I'm afraid you missed my point, it was the exact opposite.  T'vaoan is already so specialized that no one plays it, and this change will make it worse.  You can "justify" all of the creatures boons until eternity, but it seems to me that nothing will ever be good enough.  It ain't just AI you're fighting against, covenant want to have fun too.

**Comment by CommodoSeven** [comment]
Quite true. You have a new player here who speaks about his personal experience about t'vaoan and how daunting it can be to play the class. The fact that the species is rarely picked provides further proof that the role, at the moment, is far too specialised and penalised to effectively work as anything but a sniper and even that is about to change should the proposed change go through.

People who are part of the covenant and have played the role before are giving you their very own input and experiences regarding what it feels like to play it. Furthermore compromises are being offered to make the role enjoyable for those playing the role and its opponents.

I do not believe it is necessary to make a role overly complicated or tedious to play, for it to be fair and balanced. So a more suitable solution would be to figure out a way to ensure the role gets to be more than just a sniper. If you have any personal suggestions regarding that matter, I would very much like to hear them. Especially if they do not just contain upping how much damage they receive.

**Comment by caelaislinn** [comment]
SRS will be getting an indirect nerf soon, along with other UNSC weapons. When I add a cargo system I'm planning  to remove all ammo crafting from autolathes which will make heavy weapon ammo much rarer. 

I'm not convinced this change is necessary, as the tvoans are already in the ballpark of what we want. 1.1x burnmod, 1.1x brutemod, -1 slowdown, 0.3 equipment slowdown modifier (I don't agree with this) and 0.9x painmod (I don't agree with this but it's to remain in fighting condition while damaged due to increased squishiness).

**Comment by caelaislinn** [comment]
Another point, all whitelisted roles have a minimum skill expectation. We even used to do tryouts haha. Tvoans currently only have general Covenant faction whitelist but the skill expectation still remains the same. New players should be going ruuhtian, unggoy, yanmee or jiralhanae. As a glass cannon the tvoans should be the highest risk/reward in all the Covenant races.

**Comment by loafe** [comment]
Cael, with all due respect, wouldn't the nerf to UNSC weapons make this problem even worse? T'vaoans are already at a significant advantage due to their speed, and for being a glass cannon, a 10% increase in damage from weapons is not that much, and they are still able to tank a pretty significant amount of damage, especially due to their armor. If UNSC weapons are going to get worse, T'vaoans are going to be very hard to kill unless the person playing them is incredibly unrobust, no matter how they play. 

The entire concept of a glass cannon is being the main damage dealer while other classes eat the damage, but a T'vaoan can handle damage as well as a given marine, taking ever so slightly more damage.

**Comment by loafe** [comment]
As another point: we can just test this damage increase, and if it becomes too bad for T'vaoans, the change can be reverted.

**Comment by Jaybirdyy** [comment]
I feel like we should probably wait for the next big update to come out, as I imagine that will shift gameplay a bit.

**Comment by caelaislinn** [comment]
A glass cannon is not the main damage dealer, it's a specialist high damage class. Your main damage dealers will usually be mid liners who are a) numerous b) can tank a bit of damage (due to being hybrid or jack of all trades) c) deal reliable, consistent damage. So jiralhanae, sangheili and unggoy. 

Again, tvoans are high risk/high reward, and high risk things have a high chance of failure. As they are infrequently played I think it's safe to say most Covenant players consider them unfun or too hard already.

**Comment by Jaybirdyy** [comment]
I'd also argue that from what I've seen, unggoy are hardly able to give consistent damage, but that's beside the point of this GIT.

**Comment by Sgtwok** [comment]
You go on about grace shots, ignoring that the DMR, with Armor penetration, is a thing.

**Comment by Delnth** [comment]
Let's remind ourselves of what happened the last time we nerfed T'Vaoans, they became unplayable because a single bullet was such a significant deal that it usually caused their death. There are a myriad of ways to counter T'vaoan, even if most of them are hardly applicable amidst the fight. But as far as I know, it doesn't kill to throw a smoke. I believe I know what this "complaint" stems from, and punishing a role because a player has mastered their positioning, simply isn't the answer.

If I happen to be wrong in regards to the context of this issue, it doesn't change much. Throw a smoke, rush the sniper or put a lot of pressure on it. Or take cover and deal with other threats if possible. T'Vaoan speed has been so significantly reduced it's the reason we only have 1-2 mains left in the faction, as stupid as it may sound. Nerfing them further will simply make them even more unplayable, potentially. There is already little to no reason to pick T'Vaoan because elite/brute/shield kiggie perform better in most situations.
