### ISSUE TITLE
Grunt Suit Slot Sadness

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#2645]
#### Description of issue
Grunts suit storage is filled with an invisible methane tank

#### Difference between expected and actual behavior
Grunt backpack tank should be the methane source instead, and their suit storage should be freed up to store things

at request, this is the compiled list of things the suit storage should reasonably hold:
-non heavy weapons, 
-grenades, 
-pill bottles/syringes

minor addendum:
grunt backpack tank probably shouldn't fit in suit storage (it currently does), that's silly

#### Steps to reproduce 
be grunt
attempt to store stuff and things in suit storage
experience the most pure and finely crafted depression man could ever produce

please, help these grunt orphans find a better life, let them store slightly more today, just by donating 1 like you can extend their lifespans by 5 seconds

**Comment by caelaislinn** [comment]
The grunt methane tank can currently fit in the backpack slot or suit storage slot, but spawns in the backpack slot. I'm not sure what you're asking

**Comment by 24THBN** [comment]
I think he is asking to let us put non-heavy weapons, grenades, pills bottles/syringes on the suitslots, since we are unable to put anything there as Grunt, which is odd.

Apparently there is something on the suit slot that is invincible or something, and the only thing that fits there is the Methane tank.
