### ISSUE TITLE
Plasma Grenades

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2685]
#### Description of issue

Playing the game over the recent weeks, one thing has stood out to me as inherently unbalanced, that being plasma grenades. 

The entire premise of cooking a grenade and throwing it is tossed out the window in favor of sticking, which with a 100% chance, ashes the limb it is attached to, and often equipment. For a marine, this is pretty much an instantly kill, with Spartans still dying pretty frequently from this. 

On the other hand, the UNSC grenade is very underwhelming. I have stood on frag grenades a few times and been fine, and to use them effectively you have to either be very lucky or be very good at timing, since grenades can be inconsistent in fuse timers. 

Getting stuck by a constantly respawning suicide grunt carrying 4 grenades isn't fun in the slightest, and while I'm sure I will get a list of reasons in which they are ineffective and actually need to be buffed, the reality is that most combat happens within 5-6 tiles, and in that range plasma grenades are the most lethal weapon in the game. 

So how do we change it? There are a few ways, all of which I am open to. The first way is eliminating the ashing effect grenades have. This is the simplest, but not the best, as it does make the grenade pretty weak, as the UNSC grenade has the ability to (in very unlikely circumstances) to gib a limb. 

The second way is to reduce stick chance. This was tried in the past, but the Covenant players complained that it made grenades nearly effective. While I disagree with this idea, the game is about having fun, and if they are not fun to play with, they are not fun to play with. 

The third and final way I will propose is making them have an arm time before they are able to stick, a couple seconds or something. This will give the UNSC player a warning that a grenade is about to fucking rail them, and that they should probably put on the jukes. If after that the Covenant are still able to stick them, more power to them. This is the best option in my opinion, because it makes it simulates the warning someone would have by a grenade being armed and thrown at them, rather than just being instantly stuck and dead before they can physically react. 

I'd love to hear alternatives, if you have any.

**Comment by Sgtwok** [comment]
Plasma grenades do 65 points of damage.

Honestly I believe there's way too many explosives in general, and given how lethal they are now? It's bad. At any time you can die instantly.

**Comment by 24THBN** [comment]
It does 60.

**Comment by loafe** [comment]
And yet it do still be ashin limbs every time someone gets stuck unless its the chest, including the head, and it ashes equipment away including headsets and undersuits. the damage isn't what kills you its not having a leg or arm or head

**Comment by Sgtwok** [comment]
I've.. *NEVER* seen equipment get outright deleted, though that's thanks to the autism that is SS13 spaghetti code, it might only apply to the chest, in which case a common 200 HP marine can just shrug it off, or it may target a hand, multiple arms, the head, the lower body...

**Comment by Joe44445** [comment]
Today I shall ash the limb I hit and also ash unrelated gear (looking at you, spartan undersuit) whilst also being extremely readily available (looking at you, suicide grunts)

anyone who thinks grenades ashing limbs and having a 100% stick chance is fun needs to rethink something becuase that ain't it chief

it isn't fun to fight

it isn't even fun to use, atleast not to me

a nerf'd be good, either the one suggested by Loafe or any others suggested, currently it's just people spawning and suicide grunts and killing people. This, if done  to someone such as a new player, will easily cause them to leave. Hell, it makes me want to leave sometimes
"Haha funny plasma nade stuck me and ashed my leg which caused the covenant to kill me without me even having a chance to either fight back or attempt to flee, guess i'll just go play some other game"
people will just leave with stuff like this in the game. Having equipment ashed, especially as a spartan where you physically cannot get new gear and everything else looks janky as fuck to you, is way more powerful than ANYTHING the UNSC grenade could do to you.

**Comment by Sgtwok** [comment]
The plasma grenade has already been nerfed into the ground, the SRS literally does more damage.

Again, it needs more of a rework thanks to randomly targetting limbs instead of directly just dealing damage, the SSR has this problem as well, as we've had people who've straight up been gibbed, to say nothing of the UBGL instantly killing people or the Concussion rifle rendering people to the healthy state of dead.

**Comment by loafe** [comment]
this thread isn't about the srs, the ubgl or the spankr

you have yet to really address how the current plasma grenade is a fair and balanced game mechanic

**Comment by Sgtwok** [comment]
I'm not surprised you missed my point.

Again, it does very little damage in the grand scheme of human health values, the problem is it randomly selects limbs. To lower the damage from 60 so that it would not be capable of ashing limbs would be so low that we'd be better off charging people with the energy dagger.

It needs a rework. Not a nerf.

**Comment by loafe** [comment]
you mean the rework like I suggested where it has a 2 second timer before its able to stick

**Comment by Sgtwok** [comment]
That.. Wouldn't change anything unless someone just has THAT small of a window of time to act.

**Comment by Joe44445** [comment]
"that small a window to react"

it is, quite litreally, pretty much half the actual fuse on a grenade.

the goal of the stick timer would be to give people a chance to see the grenade light up in the hand and have atleast a few seconds to atleast ATTEMPT to book it

right now it's
Arm
Throw instantly
Stick
Ashed limb
which is very fun and balanced when it comes to counter play.

**Comment by Sgtwok** [comment]
I believe heavy, direct damage to the torso would be far more balanced, it would hurt, but you aren't going to die unless you are hurt that badly already.

**Comment by ghost** [comment]
suicide grunts are perfectly balanced

**Comment by Delnth** [comment]
Body part loss in general is pretty annoying. That's why I prefer /tg/station med system. You don't get your limbs ashed/gibbed when shot or caught in an explosion (unless you are at the epicenter for the latter) unless sharp melee weapon is used. Fun over realism and all that jig. But some people enjoy the "complex" mechanics that baymed has to offer, even if that mean there has to be a player incapacitated for an extended period of time without any way of doing anything.

The plasma grenade has always been a controversial topic. We even went as far as to strip it of what made it a sticky nade: removing the 100% stick chance, decreasing the range, lowering it's damage/radius. And it became useless, nobody used it anymore. And when it is overperforming, people use it way too regularly.

My two cents being: we could either disable body part ashing/gibbing (you can't remove this effect from the grenade, it's a feature of baymed where, once a limb exceed the damage threshold, it's deleted) or make them rarer (however I doubt that'd solve the issue because all it takes is one lucky, well placed grenade to dunk on someone). I don't know if significantly lowering the damage would satisfy everyone, in order to favor the utility (knockdown + knockback) over instant damage, but that could be an idea.

Edit: A rework suggests a significantly different function/behavior. However the plasma grenade is not a complex mechanism, its function is too simple to make it an elaborated tool.

**Comment by X0-11** [comment]
the damage is currently supplemented by a semi-effective explosion hit. The direct damage could be lowered and the severity of the explosion hit increased by one.
