### ISSUE TITLE
Add recharger to ONI base

### ISSUE THREAD

**Issue by loafe** [HaloSpaceStation/HaloSpaceStation13#2692]
#### Description of issue
Currently UNSC weapons can only be charged in the PD, which doesn't really make sense. One or two rechargers in ONI base for UNSC weapons would be ideal

**Comment by CommanderXor** [comment]
Didn't Cael add in plasma rechargers into the research list for the plasma batteries? I remember it being present in the test-builds.

**Comment by Delnth** [comment]
I've seen two types of rechargers in the list of the circuit board printer. I don't remember the exact names but one of them should work for weapons.

**Comment by caelaislinn** [comment]
There are two types of "rechargers" unlocked by default, these are the two vanilla SS13 rechargers `/obj/machinery/recharger` which accepts 
- /obj/item/weapon/gun/energy (except for Covenant plasma weapons... should support UNSC splaser and UNSC railrifle)
- /obj/item/weapon/gun/magnetic/railgun (vanilla SS13 gun)
- /obj/item/weapon/melee/baton (including UNSC humbler stunbaton)
- /obj/item/weapon/cell
- /obj/item/modular_computer/
- /obj/item/device/suit_sensor_jammer (not ordinarily accessible, from vanilla SS13)
- /obj/item/weapon/computer_hardware/battery_module
- /obj/item/weapon/shield_diffuser (not ordinarily accessible, from vanilla SS13)

The other vanilla SS13 charger is `/obj/machinery/recharger/wallcharger` which accepts
- /obj/item/weapon/gun/magnetic/railgun
- /obj/item/weapon/gun/energy
- /obj/item/weapon/melee/baton

Circuitboards for both of these are printable from the circuit printer at round start. I didn't map any in because the UNSC doesn't get anything at roundstart needing charging except computers, cells and possibly batons none of which are used regularly. 

The two UNSC plasma guns unlocked through research `/obj/item/weapon/gun/energy/unsc_plasma` and `/obj/item/weapon/gun/energy/unsc_plasma/marksman` have a special plasma cell `/obj/item/unsc_plasma_cell` and can be charged in `/obj/machinery/unsc_plasma_charger` all of which are unlocked through research.
