### ISSUE TITLE
[Bug] Dropship gamebreaking issues

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#2695]
#### Description of issue

From what I've witnessed so far:
- Destroying a dropship makes the Remove-cargo verb disappear (witnessed on a spirit)
- Deploying a dropship sometimes makes the Remove-cargo verb disappear (witnessed on a pelican)
- Deploying a dropship does not send a notification in dead chat; ie if you deploy for the first time, it'll lock in place, the second time will indeed send a notification in dead chat, but the second activation is in fact not the deployed state (witnessed on a pelican)
- Deployed dropships are sometimes still "flying" despite not being piloted, in the air or showing the proper alpha (witnessed on pelican and spirit)

#### Specific information for locating

/obj/vehicles/air/overmap/spirit_dropship
/obj/vehicles/air/overmap/pelican/unsc

#### Length of time in which bug has been known to occur

Unknown

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: ea21ec16334e470ba7cc463f37b5ec0be7c08084 - alpha - 
Game ID: b8e-cYJQ
Current map: Geminus Colony

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by ondrej008** [comment]
> Destroying a dropship makes the Remove-cargo verb disappear (witnessed on a spirit)

Don't know if you're referring to the round where the artifact became stuck, but that's because someone tried to retrieve the artifact, while inside the Spirit, the artifact was removed from the retrieve-cargo list, but it was still inside the Spirit and an admin had to get it out.

**Comment by caelaislinn** [comment]
Yikes ok, I've got some fixes for this coming up shortly.

**Comment by caelaislinn** [comment]
I wasn't able to reproduce the Remove-cargo verb disappearing at the wrong times... it appeared to be correctly appearing or hiding itself based on whether there was cargo in the vehicle or not. 

Instead of making it possible to deconstruct or unload vehicle debris (which I'd like to do in a future update) I just made vehicles dump all their cargo when destroyed. Should be a little easier although I'm foreseeing a potential problem with dumped items being "stuck" and inaccessible under the debris. I'll come back and look at that later

I found and addressed the other issues.
