### ISSUE TITLE
Yanme'e Flight Does Not Reset on Landing

### ISSUE THREAD

**Issue by CommanderXor** [HaloSpaceStation/HaloSpaceStation13#3159]
#### The Yanme'e flight timer does not seem to reset on landing per the arranged compromise when flight was issued in the first place where they would have smaller flight pool but instant regeneration when flight was modified and added in with jetpacks.

Description of issue:
Yanme'e were originally meant to have 20 less flight units then jetpacks but would instantly regenerate on landing, where jetpacks are meant to recharge over time.

As it stands, they do not instantly regenerate flight ticks, and also have a larger than intended pool.

Difference between actual and intended:
Activate wings, see that you do not regenerate instantly upon landing.

Where it might be located:
Pretty simple, likely due to how the new wing system is handled.

How old is the issue:
Since the wing update was added in.

Client version, Server revision & Game ID:
Client ID: 514
Server Revision: Server Revision: b7bbc9490018b3e415bd0833511c9f055cc025f1 - alpha - 
Game ID: cgy-bcea

Issue bingo:

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by Aroliacue** [comment]
My notes on this: There is a moment's pause where you cannot move after landing, and usually there's no way to avoid it - However, you can activate your jetpack immediately afterwards and continue moving. If Yanme'e flight regeneration is made truly instantaneous (rather than having a, say, 2-3 second delay) then they'll basically be able to fly forever. I have my own personal gripes with balancing behind making flight regeneration instantaneous for a species that are as physically strong (or rather weak) as a Kig-Yar, but that's not relevant to this issue.

In any case, this is a coding issue of course, so it's up to XO or another coder to adjust the flight timer and regeneration speed accordingly.

**Comment by BebesKidz** [comment]
From someone who plays Yanme'e often: don't change it, or at least not like this.

Yanme'e are excellent flyers as they are, and the larger flight pool is well worth not having an instant recharge, and makes Yanme'e better in the air than any other race (as they should be). While instant recharge at the cost of a much lower flight pool sounds like a buff, it'd really cripple them. Why? Flight stun. Each time you land, you spend a few seconds on the ground completely immobile. Couple that with a flight time now cut to 1/3rd of what it is, and you'd see drones perpetually pinned to the ground the moment any gunfire is put on them, which would be the opposite of why you'd add instant regen. My playstyle often has me nursing my flight time so I control when and where I land, because that's how you stay alive. Though some people disagree, Yanme'e are always ever 3 seconds away from paincrit, and it's often those 3 seconds they are caught on the ground after being grounded from gunfire that they die.

So we should just keep the large flight pool, unless we want to nerf Yanme'e (please don't, even Sangheili and Spartans can use thrusters).

No need for instant regeneration or playing with the flight time. With the stun mechanic, even that instant regeneration won't save them. They would probably get outperformed by jetpacks on the basis that they'd be the first to be the first to run out of flight, and in those few seconds be gunned down.

**Comment by rtlui** [comment]
Reminder that this "compromise" no longer existed even before the wing updates, the yanmee flight has been better than the jetpacks in every way possible, even flight time for a looooong time(they basically buffed the flight time but for some reason didnt remove the instant recharge), so they do NOT need that to come back


To give details: jetpacks have 65 ticks of flight time, yanmee wings and old yanmee flight have a whooping 80 ticks of flight time

**Comment by BebesKidz** [comment]
It's not better in every way possible. It's only slightly better flight time and no damage from falling if you mismanage your flight. There's no regen bonus or speed boost, it's just a little more flight time.
