### ISSUE TITLE
REMOVE ZUHMED

### ISSUE THREAD

**Issue by Nightspark43** [HaloSpaceStation/HaloSpaceStation13#638]
I don't care if this is seen as salt, but having the server use ZuhMed is legitimately the worst idea possible, I very highly recommend the server be changed to use an older Baystation style of medical, as it's faster, easier, and all around not the worst idea came up with by anyone in this game ever.

**Comment by caelaislinn** [comment]
It's been on the backburner to fix permacrit by making the brain asphyxiate instantly for some time eg #307  The medical system is complex so it's not an easy change. Replacing the entire medical system is a huge task and not one we're going to do. I'll leave this open as a reminder to increase the brain asphyxiate rate.

**Comment by bloxgate** [comment]
As a short term compromise, maybe we could lower the point at which you can succumb? And make it clear that it's allowed.

At the moment you have to reach the massive brain damage point to be able to do so, and the message you get doesn't make it clear that you can.

Perhaps we could change the check to be half its current value (and of course still make sure they're in crit when they try do, we don't want someone getting conked in the head and deciding to respawn so that they can use computers again).

**Comment by BDpuffy420** [comment]
non-issue
