### ISSUE TITLE
[Suggestion] Elite / Covenant self-regeneration

### ISSUE THREAD

**Issue by Delnth** [HaloSpaceStation/HaloSpaceStation13#780]
Have Elite or general covenant heal over time, albeit slowly enough not to turn the tide of a battle, but fast enough not let them die of their wounds. This is a feature that would activate itself when an Elite leaves the combat zone to recover and come back. It wouldn't help in a fight anyway.

It could fix bleeding after a short period of time, as well as internal bleeding and potentially broken bones. Physical / burn damage should not be affected and shrapnel can be removed manually. As in, this feature would more or less fix the nasty damages over time and, perhaps for the Elites, a minor amount of every damages.

**Comment by caelaislinn** [comment]
Clever idea. It's a way for us to get around the Elites disliking medical attention and seeing their own spilt blood as dishonourable. 

Of course in the lore they had honourable suicide as a preferential option instead of this...

**Comment by Flaksim** [comment]
Its a clever idea, but I dislike it because it will only make an already powerful role even more powerful, elites already have regenerating shields, lunge, improved stats... to also give them regenerating health.... Pretty unbalanced.

**Comment by caelaislinn** [comment]
The HP regen would only be in a non combat area. Perhaps they could go and lie down on beds to gain the faster heal? It would still take the player out of the round for a while, but wouldn't mean the player is expected to honourably seppuku (while still leaving seppuku as an option)

**Comment by Delnth** [comment]
Could work, yes. The idea is to have a regen features that would stop the internal bleeding at some point. Bleeding externally, alright, why not, it will heal over time and eating works like a charm. My point is, when an Elite charges into the lines, and they get severely wounded. They have no way to survive because they do not use any medicine in any way, shape or form. There has to be an effective way for them to survive, without actually healing all of their injuries.

**Comment by Max-023** [comment]
With what Flak said. Elites already get shields to tank damage, higher accuracy weapons, and weapons that paincrit very quickly. The idea of allowing them to totally negate damage, even if slowly, is a bit much in my mind. Humans are still struggling with their resources to make sure at least a majority of soldiers could survive. The Covenant can make sure all of their manpower is in top shape by literally doing nothing. I would much rather have a system that punishes over aggression for Elites rather than rewarding it.

**Comment by Maxattacker** [comment]
Could add a covenant version of bio-foam that would fix arterial wounds and internal bleeding. I realize that this may or may not be "lore friendly" but it would impact covenant gameplay more positively.

**Comment by ghost** [comment]
To give my own opinion on this:

Elites already have regeneration that, as far as I know, is constantly active. It doesn't heal internal wounds to my knowledge, but it's rather effective, especially considering an Elite can quite literally survive the ONI nuke's detonation.

If an Elite, a squad or even faction leader that should be careful about how much they endanger themselves, and only expose themselves to fire in the case of briefly shielding an ally or when charging a minimally defended position while supported, manages to overextend, have their shields overloaded, and take enough damage through their armour to suffer broken bones, injured organs, internal bleeding, and whatnot, then they should in all honesty be doomed to death. 

Elites are very powerful. I'll be the first to say that, as someone who's played them multiple times in the past. The only times I've died or taken severe injuries as an Elite, and speaking as an unskilled player, have when I've been remarkably stupid and overestimated my abilities, and my shields.

While I certainly can't speak for others, I personally find that the problem with Elites seemingly being cut down rather easily is due to players being relatively unskilled and unused to using them. If we compare them to the ODSTs, who are not only experienced players, but players who are very experienced with their own roles and combat while playing them, I'd bet on the ODST winning that engagement. I have little doubt in my mind that an Elite's equipment and racial abilities place it high above an ODST mechanically, but the player's own skill is a serious factor in their effectiveness.

I'd recommend that any balancing, especially to buff them, should be done after we've had a week or two of a dedicated UNSC versus Covenant mode, where data will be more easily gathered, and more importantly, people play Elites on a regular enough basis to become skilled with them. That's when I believe it'd be fair, and more importantly feasible, to take a serious look at Elites.

**Comment by Flaksim** [comment]
Exibit A as to covenant elites having medics: https://m.youtube.com/watch?v=DPe3pnO31Tw
The argument that elites dont have medics or access to medical care because of "honor" is moot. Even the lore clearly disagrees.

**Comment by ghost** [comment]
@Flaksim 
That's post war. Non applicable pre and during the human-covvie war, which is where the modes take place.

**Comment by Flaksim** [comment]
It stands to reason that they also had medics before the events outlined in halo 5 took place.

“Cham 'Lokeema is a Sangheili medic in the service of the Swords of Sanghelios. He broke the old taboo of Sangheili medics being a sign of dishonor, and took great pride in it.”

Medics were clearly a thing during the war and most likely pre war, but considered dishonorable. Thus the elite players clearly have a choice, be dishonorable and get medical attention or die honorably. A regeneration code for them is totally out of whack both lore and gameplay wise.

**Comment by ghost** [comment]
Except it doesn't. Post war, the Swords question their prior rules and regulations, especially those tied into religion due to the Prophets' betrayal. During the war, they were tied far more closely to those rules and the 'honour' of their actions and beliefs. Post war examples show a far different reality and definitely won't be very accurate towards conduct during the war.

Take an example during the war, and it may be applicable, though it was mentioned in the Contact Harvest book that Prophets do accept herbal medicine from 'apothecaries', though the race of those apothecaries isn't disclosed, as far as  I remember. 

It's not just a lore issue, which if it was purely a lore issue, then they definitely wouldn't have medics outside of a post-war setting. It's also a balance issue. I still caution against making Elites more mechanically powerful before they're used in a regular mode and see more widespread use, as well as their players becoming more experienced and skilled with their usage, as detailed in my earlier post.
