### ISSUE TITLE
Knives and Machetes

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#782]
_The lone Marine watched the Covenant around her carefully. Captured and stripped of her shotgun, she had a plan.The other were too injured and the alien bastards tried their best to stabilize them for future interrogation. She wouldn't let that happen while she was awake. She undid her restraints slowly. A tall Sangheili clad in blue plates fashioned to his body clumsily sorted through a medkit for something to keep the ODST alive was not two feet away from her. She could see a purple, midget alien wearing in red nearby also working. The other guards were away. She knew she had to act fast. She had gone through the plan in her head over and over. Her trusty know and Magnum at the ready in their holsters. Even her armor was still on her._

_She slipped through the restraint quietly and drew her knife. Flipping it to a revserse grip, she got into a standing position. The Elite had yet to notice her. She took a breath and counted to three._

_One_

_Two_

**_Three_**

_She whipped up and moved her knife to the kneck of the oversized Gecko and plunged it in deep. It let out a gurgled cry and she pushed off of it. Like a cowboy, her pistol flew out of its holster and blasted the Grunt in one fluid motion. He was unlucky enough to turn around as he heard a struggle, his skull caving in from the .50 caliber bullet exploding between his eyes. She then turned around as the Elite finally got his claws round the knife and pulled it out. She pulled out one of her grenades and rolled it between his feet. As he stood up it set off, knocking him and his shields down. She emptied the magazine into the thing in blind fury. She came to her senses when her sidearm kept clicking and it slumped on the ground, the long neck losing its strength to hold the massive head._

_She looked at the remaining ODST the Major had been working on. He was passing in and out of consciousness. She ran over and helped him, the two preparing for the game of survival ahead of them._

Except it didn't happen. Instead her knife bounced off the energy shield the Minor had. She desperately reached for her magnum, but the thing just grabbed its plasma rifle, fired a couple shots, and returned to his work, the hopeless Marine falling to the ground, smoke rising from her chest.

Knives and to an extent Machetes always ignored shields. Why should that change here? It isn't necessary OP for the blades to hurt people. The UNSC and URF don't have knight suits to block knives either. The knives just seem like a backup to use to finish a criticaled opponent to keep him down. You gain nothing by trying to engage Elites in close quarters as their shields just tank the hit. Meanwhile their own swords and knives bypass armor like a fart through jeans. This wouldn't negatively effect grunts, bugs, Jackals, or Hunters as the Elites are the only ones with energy shielding. I do think combat knives and Machetes should pass through energy shields. Instead we have to a very large amount of raw damage to drop the shields before we even think about hurting the Elite. That just ain't fair.

**Comment by Cynliax** [comment]
Very much support, support because realistic to lore and cool moments fighting ayylmaos.

**Comment by ghost** [comment]
I think this is going to lead to people abandoning their guns and just engaging Elites in melee, which seems a little bit silly. You rushed an Elite Minor with your knife and got gunned down for your trouble. I don't believe it should be feasible for humans to engage Covenant in melee unless it's a grunt or a jackal, or they're playing a Spartan. 

Elites are these massive creatures that easily overpower humans in terms of strength. I think it should be actively discouraged to engage, or allow them to engage in melee. 

That said, you also mentioned that it takes a large amount of raw damage to drop the shields, and that isn't fair. For reference, since I was the Elite in question, you hit me with a knife and it dropped me to 70% shields. A shotgun slug immediately drops an Elite Major's shields to 50%. 
It's asymmetrical balance, and I'm not going to sugarcoat it. 

Elites are flat out better than standard humans in terms of stats, and definitely Marines in terms of equipment. You need ODSTs or a Spartan to deal with them. Not because ODSTs are all that better equipped than Marines-They're not much, their armour is slightly better and has EVA capabilities-But they have a generally high level of experience and skill and tend to beat Elites that they go up against the majority of the time.

I do think Spartans need additional melee damage, both unarmed and armed, though. So do Elites and Brutes. Because they're incredibly muscled murder machines, all of them quite a bit larger than a human.

**Comment by Max-023** [comment]
Well I don't think it will have that effect. Not many people really pay attention to these things and those that do, know that bumrushing people would pain crit weapons is a bad idea. It wouldn't shift the meta to that or even make the shotgun useless. The shotgun has slugs that removes limbs and has powerful buck that stops anything. The knife is a backup, it will just be viable if you have nothing else.

It is discouraged. Elites have swords and daggers that knock you down and ignore armor with shields to back it up soaking knives bypass shields doesn't change that meta.

Quick note, one knife hit didn't drop you to 70%, I hit you three times. That is 10% each swing. I would have to hit you ten times before I would even hurt you. That is not quick at all.

While ODSTs offer more skill and better armor (I am one of them) having skill doesn't make it up when you are backed into a corner and have to choose between a M6D with HE or a chat knife, tryingbto escape an Elite. Even Hill wouldn't get out of that scenario. This just gives them a fighring chance. Knives and Machetes don't have the slice rates to remove people's heads as quickly as an Esword. It wouldn't discredit the Elite or change anything other than the usage of the knife as a combat weapon rather than a tool to make sure criticaled people die faster.
