### ISSUE TITLE
MAC projectiles look like laser beams

### ISSUE THREAD

**Issue by caelaislinn** [HaloSpaceStation/HaloSpaceStation13#799]
They should look like slugs or some kind of projectile. A tracer is ok but they definitely need a projectile. At the moment they look like pink lasers which makes them resemble covenant weapons

**Comment by Flaksim** [comment]
That is... odd. See attached file to see what a MAC projectile looks like when fired at the moment:
Are you certain this is an issue? Because its nothing like what you described.
![2018-09-20_14h58_36](https://user-images.githubusercontent.com/38115338/45819861-b1200b00-bce5-11e8-97b4-b2d857277829.png)

**Comment by BDpuffy420** [comment]
This has been yet to be reproduced
