### ISSUE TITLE
Skirmishers' innate speed is negated when using standard loadouts

### ISSUE THREAD

**Issue by SpiderPsycho** [HaloSpaceStation/HaloSpaceStation13#821]
If a Skirmisher has a carbine, pistol, mag and e-dagger, they are essentially slowed to the point of being as slow as humans or grunts. I doubt this was how it was meant to work, seeing as they're fast when they don't have anything on at all, faster than humans with nothing on. Seems to be half-implimented or just bugged.

I was told to make this a git issue so it would be seen so sorry if the format is fuckled with. # #

**Comment by Flaksim** [comment]
I went through the entire codebase and looked at each slowdown instance.
Nothing suggests a slowdown should be happening in the code.

I then loaded up a local copy and tested this. I couldnt notice a change in speed between:
- Being a naked skirmisher.
- Being a clothed but unequipped skirmisher.
- Being a clothed skirmisher with a carbine on my back slot and a pistol on my belt, along with 2 grenades in my pockets.
- Being a clothed skirmisher with a carbine on my back slot and a pistol on my belt, along with 2 grenades in my pockets, along with several grenades and spare ammo clips in a bandolier attached to my suit.

During testing I both checked for the "feeling" of movement, and checking the actual movespeed of my character through the vars.
My conclusion based on the above: There is no slowdown because of the equipment a kig-yar carries. Unless they are using a backpack and carrying the equivalent of 2 normal items or more.

NOTE: The speed modifiers are: "Kig-Yar": -1.5   "Tvaoan Kig-Yar": -1.75
-1 is to compensate for the lack of shoes, so the actual speed increase compared to a human not bearing a heavy load in a backpack (or otherwise items slowing you down) is 0.5 and 0.75 respectively.

Given  those numbers it is likely that what the user perceived as a slowdown could have been server conditions at the time

**Comment by SpiderPsycho** [comment]
Well I'll just comment what we eventually found out it was:

Guns have a larger affect on weight than other items. It was dropping the plasma pistol that meant you were faster. Essentially, if you want to be fast, you cannot have a sidearm. Which is fair enough, until you realize that Skirmishers are meant to flank and you can't have a carbine if you want to use the shield. I suppose its up to the coders to see what they want to do with this.

**Comment by caelaislinn** [comment]
This should be addressed with the carry weight tweaks in #943 and #923
