### ISSUE TITLE
Cross Faction Whitelisting Suggestion (And Some Others)

### ISSUE THREAD

**Issue by Max-023** [HaloSpaceStation/HaloSpaceStation13#825]
We all know what it really is. It would give the ability for UNSC and URF to play the Covies.

Currently the Covenant are whitelist only. On order to get in, you need a quarter baked attempt to get in. Ideally, you should know Covenant lore, but it has since not been much of a thing. Most of the Covies got in with low effort because that's all they really get. They rarely ever get competent people, let alone people straight from the salt mines. This has resulted in a lot of careless players who do little and die.

This could be solved in theory by cross faction whitelisting. The current whitelists are ODSTs, server side, but eith the forums comes lists of URF and UNSC members. That means they can't apply for covenant either.

By allowing cross whitelisting, it would bolster the ranks of the Covenant without actually bringing in new hubbies. There are quite a few ODSTs would would love to play a few Covenant rounds and given how strong most of the ODSTs are, this would benefit the Covies from a meta'd combat aspect as well. Seriously. This has no downsides and gives players even more freedom to choose what they want to be.

Next is to unwhitelist Unggoy Minors. This is a suggestion that might be bad, but also good. The UNSC and URF get Marines and Insurrectionists from hubbies and people without ODST whitelisting for the most part. They have relatively low responsibilities so they work as a role.

The Unggoy minor is the counterpart to the Marine and Insurrectionist. This would allow people to try out the Covies without having to go through the elaborate process of getting approved and waiting just to play something they don't like. The only issue I can see are shitters, but that is a problem for the other factions as well so it wouldn't just be a Covie thing.

The last suggestion is making the Hurgok not only a role in the Covies but able to understand Common and Covenant. There are people who want to be engineers. The sprite is already in. All we need now is someone to give them engineering abilities. There is no downside to this as well.

These would be cool ideas to implement. People have shown a want for them and they are really mundane things. Noone would be salty if the Hurgok actually did stuff. Just think about it.

**Comment by caelaislinn** [comment]
The intent is for all basic species roles to be open. At a minimum: 
- Kig yar (shields and carbines). 
- Unggoy minors
- Sangheili minors

Probably also junior officers like majors and deacons. Special round-critical roles will probably be open to all, but we may prioritise people who are whitelisted for those roles.

**Comment by 2cwldys** [comment]
Max, I think you also lack proof of concept about the assumption of those that apply for their positions. I applied for Sangheili and indirectly the Covenant, I get no Sangheili apparently without PMing admins. I get Unggoy from the whitelist. I didn't get in with low effort but I applied and it took me at least a month or two in exact for it to be accepted, which drug on longer that it should've had to.

I support your idea about cross-whitelisting though. That would be nice to have, I did not even know why in the first place the official server for the development would limit their codebase based on 'accepted applications' for whitelist on a forum. I support cross-whitelisting entirely and letting it go free, with some sort of balancing method based on total amount of players.

I've seen an admin play as a Huragok, looked boring but it's also quite interesting if you've seen the interaction between them and the Covenant, and the Humans on Halo 3 ODST in the Superintendent AI core. If players are given the ability to play as these, it'd be exciting to see them able to do things such as opening doors and stuff. I lately figured out Plasma Pistols can fry open doors, but having a Huragok to deal with some gritty problems that are pro-UNSC, that'd be neat. Too much lately have I died or failed because the Covenant aren't fleshed out as they are supposed to be at their full lore potential. To touch on the above forementioned, I certainly don't like 1 Unggoy vs 5000 humans either, I felt like the bravest Unggoy alive in the Covenant Hegemony.

**Comment by 2cwldys** [comment]
Also about the 'understand common' , I read some lore videos about how the grunts are exposed to drugs and all sorts of stuff that makes them listen. Basically overly-lethal ADHD medicine with a stoned effect, and they take in information on the mass. And it explains in literally ALL the halo games, regardless of rank - they spoke english more of even the other NPC's you see like the Kig-yar that also serve the covenant. Most of the time they're fleeing birds that pop shot you every once in a while, baffled me to see that on the ship where they were 'interrogating' a prisoner, where they are usually held in cells as isolated beasts before being dropped into battle. Not really much different than the Unggoy I'd say, both being forced for Covenant Servitude. The ability to speak some common for all covenant races would be a big feat. as well for conclusion of this post.

**Comment by Max-023** [comment]
I really don't think Elites should be made as a basic role. This is just because how strong they are. Everything else is fine, however.




As for you, 2cwldys, Bolter has repeatedly talked about how having a coherent two sentence bio gets you an Elite. Not exactly high standards.






The engineers were made by the Forerunners to be a machine species to work on their trinkets and such. They are incredibly intelligent and can understand any device they come across and can take in massive forms of information, thus allowing for Common to at least be able to to be learned quickly, if not given to them round start.

**Comment by Nick123q23** [comment]
Right now we only intend to unwhitelist grunts and jackals, as elites are a lot more powerful, both in the hierarchy and in terms of combat

I've been a supporter of having multiple whitelists since the start, the only reason I can think of as to why we do it the way we've been doing is because whitelist code is difficult to manage

**Comment by caelaislinn** [comment]
One way we have to balance elites being stronger is for them to have limited spawns, forcing most Covenant players to go jackal and grunt. We could also prioritise whitelisted players for elite roles

**Comment by 2cwldys** [comment]
Well said! I support that entirely, kinda of a way to limit by amount of classes and total players on the server. I think it would also provide some relief to the administrators about being PMed to allow specific roles, I can only begin to imagine how annoying that task can be.

**Comment by caelaislinn** [comment]
I've got a faction whitelist implemented in #830 

Which roles will be behind the faction whitelist will evolve and change as we develop the server, with input from players. I want to strike the right balance of giving Covenant players a feeling of exclusivity while making sure they have enough people playing Covenant roles for the server community to live and thrive

**Comment by X0-11** [comment]
Faction whitelist has been implemented and many of the mentioned roles have been successfully integrated into the first contact gamemode.
