### ISSUE TITLE
T'vaoan bugs / issues

### ISSUE THREAD

**Issue by SpiderPsycho** [HaloSpaceStation/HaloSpaceStation13#919]
Alright so I'm just going to list issues with T'vaoans as they are just to get them fixed as quick as possible and so issues aren't just drowned out by other shitting on the Discord. I was told that I should make github posts for issues anyways.

- [x] T'vaoans don't have focus view, so I'm assuming that the ability is going to be replaced with that leap / speed ability I suggested 
- [x] T'vaoans speak Galcom instead of Sangheili
- [x] T'vaoans need shoes, badly. Same with Ruutians. Being stunned from picked out shrapnel or glass is reaaaaaally painful. I'm aware they speed up like mad when they have shoes on, so maybe lower the speed so that when they wear the boots they reach the old speed they had.
- [ ] Skirmisher armor needs to be spawned on the map. (Please give me Champion armor) Loadout whitelists? I don't see why there should be a restriction on it since they're not elites. (also I sprited it SO GIVE IT TO ME SCREEEEEE pleas)
- [ ] Gauntlets need to be added but I assume that's going to be added eventually.

**Comment by caelaislinn** [comment]
Thanks. Stuff gets lost or forgotten on Discord all the time... having an issue made for it means it 100% will get looked at and tagged/assigned appropriately (I edited your comment to make a checklist btw). These points are good actionable feedback and they're all going to get fixed. 

The one note is that I do want champion, probably murmillo, and maybe commando locked behind the Covenant faction whitelist. They have some sweet gear and stats compared to the Ruutians. I will probably only place skirmisher minor armour on the map... but commandos and murmillos have respawn for Operation: Red Flag (murmillos will get holos instead of shields soon... champions just get strong 300hp shields) so you can just respawn with their gear.

**Comment by SpiderPsycho** [comment]
Commandos are the ones with holograms by the way. Murmillos don't. Also champions have holograms too, as well as shields.

And I'm also whitelisted for Champion. Does that mean admins can spawn your stuff in and it'll be cool or not? I mean, Champions aren't ultras to be sure, and they're not Spartans either. I like to think of them as maybe the covenant equivalent of ODSTs in terms of power scaling.
