### ISSUE TITLE
Collosus Hyperzine Abuse

### ISSUE THREAD

**Issue by Darkking1234** [HaloSpaceStation/HaloSpaceStation13#926]
#### Description of issue

Make the collosus suit block or atleast lessen the affect hyperzine has 

#### Difference between expected and actual behavior

The collossus suit the insurrectionists currently have, is meant to be a slow but tanky piece of equipment. But due to recent events insurrectionists have started exploiting hyperzine to go at nearly zeal levels of speed while keeping the tankiness of the suit

#### Steps to reproduce 

Grab collosus
Take hyperzine
Be speedy as fuck

**Comment by CdrRiley** [comment]
1+ make it slow cuse even ODST struggel againt a really speedy boy and its kinda not realstig if a hulk of armour runs at sonic speeds

**Comment by Max-023** [comment]
Maybe delete hyperzine? It would be harder to make Colossus block the effects.

**Comment by zergursh** [comment]
> Maybe delete hyperzine? It would be harder to make Colossus block the effects.

That would just result in people using Rumble instead.

**Comment by SpiderPsycho** [comment]
Lower the overdose level or decrease its effect? The former might fuck over people who don't know about the change though, but it'd mean that the effect wouldn't be for as long and people would have to make sure they don't have any in them otherwise OD and die.

Or just give it a side effect, like a shaky screen or toxin / liver damage.

**Comment by Max-023** [comment]
Rumble kills you after a short time, however.


Adding a minor side effect would not decrease its usage as the people who use it are looking for an advantage that doesn't kill you. Making it do liver failure would just make it diet rumble, as that is how rumble kills you.


I would much rather take it out and introduce a different approach to getting a speed boost that will produce less metaing. Since the URF have Zeal Suits, they won't be down a feature until a solution is made to prevent the Colossus being paired with a powergame-y item to reduce its intended drawbacks. The current drug is just too abusable as there is no downside. Colossus armor blocks more than ODST armor and has three layers of armor, so it cannot get this advantage of speed acquired by hyperzine, which makes you faster than the Human base speed. I would also look at the possibilities of chem dispensers the other sides get to also work on powergaming solutions able to be created. In lore, the only chemically boosted individuals are Spartan IIIs, and I would like to keep it that way.

**Comment by SpiderPsycho** [comment]
Honestly I think just lowering the effect would be good. Only certain races should be fast, IE T'vaoans. Humans are all-rounders species wise and they don't have any biological disposition to any one role, its all gear. Hyperzine should boost speed only slightly, and maybe with the colossus armor, we can have some sort of special thing, IE:

"You strain against your armor!" --> Broken bones / brute / dislocating / joint-locking yourself.

**Comment by Max-023** [comment]
Humans aren't a all-round species, though. The different species aren't designed that way. Elites are far better than them in speed and everything else is the same. The gear they use isn't so much a perk as it is relatively mundane and ultimately only effective at combat with one other group, the other Human counterpart. Armor is ignored by a lot of Covenant weapons and their gear does not adequately counter energy shielding whether it be guantlets or shields, the answer to fighting those user just being "shoot them harder". Not to mention that their gear isn't special. Few weapons actually have different characteristics that differ from the normal "bullet spewing pew pew gun" with them being the SRS (which shoots through walls and can see farther in scope), the SPNKr (stuns the person hit), the grenade launcher (fires grenades instead of bullets), the M7/SOCOM (uses shrapnel instead of damage) and the M6G/SOCOM, which can either fire normal bullets or bullets that are just raw damage. Every Covenant weapon does something different and unique. The grenade sticks, the pistol can EMP, the needler tracks targets, the beam rifle is the SRS but with rechargeable ammo, the carbine is the only "projectile" weapon, the rifle is the base high damage, good accuracy weapon, and the Hunter cannon can paincrit people on impact. The only thing Humans get is just more freedom as to what shooty-shoot gun they want with more options. The innies get more armor that can make you go fast, slow, tank, and see in the dark. As of yet only special cases in the UNSC can take unique gear with an array of options as well as the URF having very limited amounts of special armor and bombs. But that is not the point of this issue post.


As for Hyperzine, the topic, I would say that is a confusing nerf you proposed. How would making yourself faster through PE drugs make you struggle with your armor physically? Unless it is a Jackal serum that makes you downgrade strength to T'Voan grade but upgrade the speed, I don't really see that making much sense.


 I still very much support removing it until something can replace it that prevents metaing. It's far better and the removal of Hyperzine also removed rumble drugs, taking out the two base performance enhancing drugs. It just is too unrestricted as of yet and a serious inhibitor to introducing nerfs, this clearly being seen as it directly counters the speed nerf the Colossus gives you, still making you go faster than base Human speed. The current UNSC official doctrine supported by the UNSC is to find a locker or crate and hide until the Colossus user runs out of Hyperzine, then engage and run. The intended tactic to fight the Colossus is to shoot and scoot, but you can't do that when the walking tank scoots faster than you and outruns you. This can't continue.

**Comment by zergursh** [comment]
https://gyazo.com/20eb69291e01db3927927410c7385ea7

**Comment by zergursh** [comment]
Hyperzine has been nerfed, only really used for reducing Collosus Slowdown now. 

execute order 66 on this issue
