### ISSUE TITLE
Add Grunt Ultras as Job on Extended

### ISSUE THREAD

**Issue by mcalexev** [HaloSpaceStation/HaloSpaceStation13#930]
So, yeah, I noticed how Elite Ultras are available, but Grunts don't have access to their equivalent, just minors and majors. Figured it'd be a nice option to have for those who'd like to have a bit more authority as an Unggoy. :)

**Comment by SpiderPsycho** [comment]
Or maybe a change in admin protocol? Maybe admins are obliged to let people play their whitelisted role, IE the one on the spreadsheet, within reason. So you can't have Hunters or Elite zealots / 5 heavy weapon grunts, but you can have one or two Ultra grunts / Champions / Commandos?

**Comment by Max-023** [comment]
I see no reason for Grunt Ultras to not be added. But adding things like Hunters, Zealots, Spec Ops, Heavy Weapons Grunts, Advanced Skirmmishers, and Shipmasters are widely unnecessary in every sense. The Infraction is a scout ship, don't you forget, not a carrier. A Ruutian priate ship to recon the system for a real invasion force. Anything more than that basic roles+Huragok+ultra Unggoy is completely unnecessary and throws balance out the window. If the UNSC can't even get a heavier vehicle than a fucking Mongoose and the URF can't set up a stealthy and hidden base of operations, you don't need champion T'vaoans. Covies already have insane ground control with their defensive tech and offensive weapons. Ya don't need more.

**Comment by SpiderPsycho** [comment]
Its a scout ship and their job is to stay hidden and undiscovered. I think they should at least have some higher ranking / competent leadership.

I just think if we have more ranks and things we'd boost our playership. Right now we have a few people ingame, with most of them just lurking and only joining when they can play super strong ranks. We can have a sort of increase in the ranks available but not all of them.

**Comment by Max-023** [comment]
And what's more competent than an Elite Ultra, Skirmmisher Shipmistress, and Unggoy Ultra? Staying hidden isn't rocket science. Yes, the Covenant is supposed to act retarded in lore, but in the server they don't. You don't need anything more than that.

**Comment by Max-023** [comment]
And increasing the different ranks doesn't mean people will flock to the Covenant more. There are plenty of UNSC jobs that are covered in an inch of dust, and those don't even need whitelists. Having an established playerbase in lower ranks is more important than giving the Elite Ultra that spawns a Zealot role.

**Comment by SpiderPsycho** [comment]
I know that Skirmishers are very specialised with their jobs, and I never said anything about Zealots. Covenant forces have varied roles depending on their rank, and the weapons vary in their function. Human weapons are usually similar, with three main differences, shotgun, sniper and every other semi-auto to auto gun. Each covie weapon has different properties.

Not to mention we don't even get events that often so its either have more events, add more roles for the Covenant or keep us stagnant and never involved.

**Comment by SpiderPsycho** [comment]
Also a key part of this is RP potential too. The RP, at least for covies, is super limited. Not only will this probably boost numbers, but it'd also boost the whole dynamic between characters

**Comment by Max-023** [comment]
Adding more roles wouldn't increase involvement. Instead of a white ultra attacking VT9, it would be gold. RoE is the issue there.


As for events, it isn't just decided "we do this with the URF on this date". The mods and admins just do whatever they feel is cool then. And I have no idea which rock you have been living over because out of the past 4 events, one was a Covie invasion of VT9.

Covie weapons are irrelevant. The Ultra Unggoy is to add secondary leadership after the Elite Ultra, not for a new weapon. The UNSC does not have role specific gear, as Marines are shoved into one role. A Marine with a shotgun isn't a different role with one with a DMR. ODSTs run with the idea of leaning towards specializations, but there is nothing stopping a rifleman using a SRS and having a MA5B as a CQC ODST is fine. I fail to see the reasoning of adding more room to the Covies because most of the gear is used. Beam rifles and energy swords are the only exception. Carbines, needlers, plasma pistols, plasma rifles, and energy daggers are already there for use and do perfectly fine. The plasma repeater would be redundant, the needle rifle would be redundant, the energy sword is currently being looked at, the fuel rod cannon is like the SPNKr right now, the beam rifle is being looked at, and the storm rifle doesn't exist yet. You aren't missing out on anything to be added with a new role. And the argument of new combat roles doing different things is muddled. What does a champion do differently from a Murmillo or the basic role for T'Vaoan? They aren't necessary for the task at hand whatsoever. I could justify a Spartan II contingent to the Bertels as well as Marine snipers, Hellbringer Marines, ONI field operators, and an Orion Marine role. They all do something different and unique on the battlefield, but they aren't warranted because the threat level ain't that high.

**Comment by Max-023** [comment]
And RP is limited as there is a dumb RoE in place as well as people not playing the game. A lack of roles doesn't attribute to this. Again, see the UNSC for a group that has a BUNCH of roles but doesn't see usage for the majority of them.

**Comment by caelaislinn** [comment]
The whitelist is for _factions_ not _roles_ and the application process being targetted to a specific role or race is so staff can review a person's RP and background knowledge. We intend that different gamemodes will have different selections of roles and species available to provide diversity in player experience

**Comment by caelaislinn** [comment]
FC mode will be redone shortly. We'll probably add playable deacons as a consolation for lack of unggoy ultras
